### ISSUE TITLE
MQTT integration failure

### ISSUE THREAD

**Issue by LouPaloma** [akasma74/Hass-Custom-Alarm#1]
**Describe the bug**
Enabling MQTT causes the alarm not to load and a log entry of "Signature of MQTT msg_callback 'custom_components.bwalarm.alarm_control_panel.message_received' is deprecated"

**To Reproduce**
1. Start with working custom alarm with MQTT off
2. Enable MQTT
3. Restart HA

**Expected behavior**
MQTT integration should work.  Alarm module should work

**Screenshots**

**Browser (please complete the following information):**
 - Firefox and Chrome

**Additional context**
Home Assistant 0.92.1

**Comment by akasma74** [comment]
Could you provide your config details?

My config:
Home Assistant: v0.92.1
This Panel: v1.3.6_ak74
Component (Bwalarm): v1.1.4_ak74
Python: v(3,7,3,final,0)

No issues with or without MQTT.

**Comment by LouPaloma** [comment]
Home Assistant: v0.92.1
This Panel: v1.3.6_ak74
Component (Bwalarm): v1.1.4_ak74
Python: v(3,5,6,final,0)

No issues without MQTT

**Comment by LouPaloma** [comment]
Don't think this is a configuration issue.  I think HA has deprecated the MQTT message approach.  Looking at the code for the standard alarm component there are relevant changes there.  See: [HA PR #21959](https://github.com/home-assistant/home-assistant/pull/21959/commits/fe870f125cdba0940a826fa1e1a6e4c70015f181#diff-3bd6f07c7418336b9faf241b58826abbl).

I'd fork your repo and test the code change myself, but my day job prevents me from getting to this before the weekend...

**Comment by akasma74** [comment]
You're more than welcome to test it yourself.
I checked 0.92.1 breaking changes and there's nothing about MQTT (but following your link I can see it's already there from 0.90.. hmm..).
However, I updated my HA to 0.92.1 and cannot reproduce the issue.

Anyway, I've just uploaded a new version of alarm_control_panel.py, could you check it out?
Mine works fine, I was able to arm my alarm via MQTT.

**Comment by LouPaloma** [comment]
So I've upgraded to HA 0.92.2 and to your latest version (v1.1.5_ak74 per source code, but UI still shows 1.1.4_ak74), but the integration still doesn't work.  I am seeing a different error on the logs now, though:

`2019-05-05 10:22:34 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/site-packages/homeassistant/helpers/entity_platform.py", line 363, in _async_add_entity
    await entity.async_added_to_hass()
  File "/usr/lib64/python3.5/asyncio/coroutines.py", line 223, in coro
    res = yield from await_meth()
  File "/usr/lib/python3.5/site-packages/homeassistant/components/mqtt/__init__.py", line 375, in async_subscribe
    async_remove = await hass.data[DATA_MQTT].async_subscribe(
KeyError: 'mqtt'`

**Comment by ame9895** [comment]
I was having this same problem with the same versions as you, @LouPaloma. In troubleshooting something completely unrelated, I removed the “deps” directory from /config and restarted HA. This fixed the MQTT problem above. Worth a shot.

**Comment by akasma74** [comment]
Huh.. my /config/deps is completely empty anyway, wonder if anyone of you guys had something in there..

**Comment by LouPaloma** [comment]
The deps directory is populated by HA upon startup.  Mine was full of files.  Deleting them only delayed HA startup until it could reinstall them.  The issue remained.

However, I've set up a new conda environment using Python 3.7.3.  Running HA under that version seems to resolve the issue.  Still testing, though...

**Comment by akasma74** [comment]
> So I've upgraded to HA 0.92.2 and to your latest version (v1.1.5_ak74 per source code, but UI still shows 1.1.4_ak74), but the integration still doesn't work.

just noticed that. you must be on **v1.1.5_ak74** for  fix to work.
try to stop HA, delete `/config/custom_components/bwalarm/\_\_pycache\_\_` folder and start HA.

**Comment by akasma74** [comment]
Any news on that?

**Comment by LouPaloma** [comment]
Been a week of running fine.  I'd say close the ticket.  Thanks.

**Comment by rrbarrero** [comment]
Hello! Can you help with this. I think its the same problem but not fixed changing Python version:

```
Traceback (most recent call last):
  File "/srv/homeassistant-3.8.1/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 406, in _async_add_entity
    await entity.async_added_to_hass()
  File "/usr/local/lib/python3.8/asyncio/coroutines.py", line 136, in coro
    res = yield from await_meth()
  File "/srv/homeassistant-3.8.1/lib/python3.8/site-packages/homeassistant/components/mqtt/__init__.py", line 433, in async_subscribe
    async_remove = await hass.data[DATA_MQTT].async_subscribe(
KeyError: 'mqtt'
```

HA version | 0.103.2
Alarm Panel: v1.11.1
This integration: v1.11.1
Tryed with Python: 3.7.1, 3.7.4 and 3.8.1.
No issues without MQTT

**Comment by akasma74** [comment]
could you please open a new issue as this one is closed?

**Comment by rrbarrero** [comment]
Sure, thank you.
