### ISSUE TITLE
Error to call service alarm_control_panel/alarm_yaml_user. 'users'

### ISSUE THREAD

**Issue by alb147** [akasma74/Hass-Custom-Alarm#101]
Hi
I receive this error every time I enter the panel.
although everything seems to work.
Can you help me see what is wrong?
Thanks

my version is:
his integration: v1.12.4
Home Assistant: v0.110.6
Python: v (3,7,7, final, 0)

LOG:

Logger: homeassistant.components.websocket_api.http.connection.1762534672
Source: custom_components/bwalarm/alarm_control_panel.py:865
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:20:53 (4 occurrences)
Last logged: 16:20:53
'users'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1290, in _execute_service
    handler.func(service_call)
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 422, in alarm_yaml_user
    alarm.settings_user(service.data.get(CONF_USER), service.data.get(CONF_COMMAND))
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 865, in settings_user
    self._yaml_content['users'].append(user)
  File "/usr/local/lib/python3.7/site-packages/ruamel/yaml/comments.py", line 752, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'users'

**Comment by akasma74** [comment]
Please post your `bwalarm.yaml` here

**Comment by alb147** [comment]
> 
> 
> Please post your `bwalarm.yaml` here

Hi,
I don't have a 'bwalarm.yaml' file in the / config folder
I have a file called 'alarm.yaml'
`##########################################################
## CUSTOM ALARM COMPONENT ALARM.YAML
## https://github.com/gazoscalvertos/Hass-Custom-Alarm
## VERSION:  1.0.2
## MODIFIED: 18/04/18
## CHANGE LOG:
## Add Multi Codes, names, pics
## optional code to arm alarm
## Default Interface password: HG28!!&dn
##########################################################

platform: bwalarm
name: House
panel:
  camera_update_interval: ''
  cameras: []
  enable_camera_panel: false
  enable_clock: 'False'
  enable_clock_12hr: 'False'
  enable_custom_panel: 'False'
  enable_floorplan_panel: 'False'
  enable_sensors_panel: 'True'
  enable_serif_font: 'True'
  enable_weather: 'False'
  hide_passcode: 'True'
  panel_title: Alarma
  shadow_effect: 'True'
  enable_fahrenheit: 'False'
states:
  armed_away:
    immediate:
    - switch.skylight
    - binary_sensor.away_sensor
    - binary_sensor.door_window_sensor_158dff4ca0f32
    delayed:
    - binary_sensor.away_delayed_sensor
    - binary_sensor.door_window_sensor_158dff4ca0f32
    override: []
    pending_time: 23
    warning_time: 35
    trigger_time: 300
  armed_home:
    immediate:
    - binary_sensor.home_sensor
    - binary_sensor.vibration_158d3223af6fb9
    delayed:
    - binary_sensor.home_delayed_sensor
    override: []
    pending_time: 5
    warning_time: 0
    trigger_time: 150
  armed_perimeter:
    immediate:
    - binary_sensor.perimeter_sensor
    delayed:
    - binary_sensor.perimeter_delayed_sensor
    override: []
    pending_time: 0
    warning_time: 2
    trigger_time: 600
users:
- id: 67f7254ae4094b3a79950b349f65f77
  name: Hass.io
  enabled: true
  code: 67f7254ae4094b3a79950b349f65f77
  picture: /local/images/ha.png
- id: 31850f86b32b4f5ba109bb8ddd23fdfb
  name: My_name
  enabled: true
  code: 31850f86b32b4f5ba109bb8ddd23fdfb
  picture: /local/images/ha.png
- id: 5477db04904534e4abff960263bc1d00
  name: Home Assistant Cast
  enabled: false
  code: 5477db04904534e4abff960263bc1d00
  picture: /local/images/ha.png
admin_password: 1234
code: '1234'
enable_perimeter_mode: false
code_to_arm: true
themes:
- name: aaa
  warning_color: '#995BFF'
  pending_color: '#FF2943'
  disarmed_color: '#FF22E6'
  triggered_color: '#FF0000'
  armed_home_color: '#C1B1FF'
  armed_away_color: '#FF8686'
  armed_perimeter_color: '#DAFF9E'
  active: false
  action_button_border_color: '#3ED5FF'
panic_code: '4321'
enable_log: true
passcode_attempts: '-1'
passcode_attempts_timeout: '10'
enable_persistence: true
`

**Comment by akasma74** [comment]
That's not good.
Please post here content of `bwalarm.yaml` from `/config/resources/bwalarm/` making sure you enclose it in three single back quotes to preserve formatting.

**Comment by akasma74** [comment]
@alb147 may I now why you closed it?

**Comment by alb147** [comment]
> @alb147 may I now why you closed it?

Yes, can close. But I other error. I create the new issue
