### ISSUE TITLE
This component is not working!

### ISSUE THREAD

**Issue by alb147** [akasma74/Hass-Custom-Alarm#104]
Home Assistant: v0.111.2
This Panel: v1.3.6_ak74

I cannot access to alarm panel:
![IMG_20200613_232025](https://user-images.githubusercontent.com/47964841/84579277-d06d9e80-adcc-11ea-9e67-af0ecea739b5.jpg)

I see this in log:
Detalles de registro (ERROR)
Logger: homeassistant.components.alarm_control_panel
Source: components/frontend/__init__.py:190
Integration: Panel de control de alarmas (documentation, issues)
First occurred: 22:14:34 (1 occurrences)
Last logged: 22:14:34

Error while setting up bwalarm platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 401, in async_setup_platform
    config={"alarmid": "alarm_control_panel.house"},
  File "/usr/src/homeassistant/homeassistant/components/panel_custom/__init__.py", line 140, in async_register_panel
    require_admin=require_admin,
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 190, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel alarm

**Comment by akasma74** [comment]
The problem is you're using a very old version of the alarm.
I'd advise to [update](https://github.com/akasma74/Hass-Custom-Alarm/releases/tag/v1.12.6) the alarm.

**Comment by alb147** [comment]
I replace all for Hass-Custom-Alarm-1.12.6
I delete the cache, restart  and the error is the same:

This component is not working!
Check the Home Assistant log for more details.

Home Assistant: v0.111.2

This Panel: v1.3.6_ak74

LOG:
Logger: homeassistant.components.alarm_control_panel
Source: components/frontend/__init__.py:190
Integration: Panel de control de alarmas (documentation, issues)
First occurred: 11:02:58 (1 occurrences)
Last logged: 11:02:58
Error while setting up bwalarm platform for alarm_control_panel

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 401, in async_setup_platform
    config={"alarmid": "alarm_control_panel.house"},
  File "/usr/src/homeassistant/homeassistant/components/panel_custom/__init__.py", line 140, in async_register_panel
    require_admin=require_admin,
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 190, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel alarm

**Comment by akasma74** [comment]
I'd suggest you to install the alarm from scratch as described [here](https://github.com/akasma74/Hass-Custom-Alarm#how-to-installation) because the v1.3.6_ak74 dates back to November 2018.
Before doing so please stop HA, backup your `bwalarm.yaml`, then remove `<HA config>/alarm.yaml`, `<HA config>/custom_components/bwalarm` folder with its content, `<HA config>/resources/bwalarm` folder with its content.

**Comment by alb147** [comment]
> I'd suggest you to install the alarm from scratch as described [here](https://github.com/akasma74/Hass-Custom-Alarm#how-to-installation) because the v1.3.6_ak74 dates back to November 2018.
> Before doing so please stop HA, backup your `bwalarm.yaml`, then remove `<HA config>/alarm.yaml`, `<HA config>/custom_components/bwalarm` folder with its content, `<HA config>/resources/bwalarm` folder with its content.

I will try. 
Thanks :)

**Comment by alb147** [comment]
> 
> 
> > I'd suggest you to install the alarm from scratch as described [here](https://github.com/akasma74/Hass-Custom-Alarm#how-to-installation) because the v1.3.6_ak74 dates back to November 2018.
> > Before doing so please stop HA, backup your `bwalarm.yaml`, then remove `<HA config>/alarm.yaml`, `<HA config>/custom_components/bwalarm` folder with its content, `<HA config>/resources/bwalarm` folder with its content.
> 
> I will try.
> Thanks :)
working fine next uninstall, clean all and install
Thanks 

> 
> 
> I'd suggest you to install the alarm from scratch as described [here](https://github.com/akasma74/Hass-Custom-Alarm#how-to-installation) because the v1.3.6_ak74 dates back to November 2018.
> Before doing so please stop HA, backup your `bwalarm.yaml`, then remove `<HA config>/alarm.yaml`, `<HA config>/custom_components/bwalarm` folder with its content, `<HA config>/resources/bwalarm` folder with its content.

**Comment by akasma74** [comment]
Cool.
Hope you're happy now ;)

**Comment by akasma74** [comment]
Cool.
Hope you're happy now ;)

**Comment by sweup** [comment]
I have the same problem, I made an uninstallation following your guide, but then when going to HACS I couldn't find your integration in the list, but thru the plus sign I could ad the BW repository and install it. Before I had the 1.12.4 version but when install it thru the repository I got the same version as above 1.3.6 - and it is the same problem as described above, ie problem still there.

Hope you could help me

`

Logger: homeassistant.components.alarm_control_panel
Source: components/frontend/__init__.py:190
Integration: Alarm control panel (documentation, issues)
First occurred: 10:02:38 PM (1 occurrences)
Last logged: 10:02:38 PM
Error while setting up bwalarm platform for alarm_control_panel

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 401, in async_setup_platform
    config={"alarmid": "alarm_control_panel.house"},
  File "/usr/src/homeassistant/homeassistant/components/panel_custom/__init__.py", line 140, in async_register_panel
    require_admin=require_admin,
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 190, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel alarm

`

**Comment by akasma74** [comment]
No offence but it looks like a HACS issue, the current version is not 1.3.6.
I'd suggest either to install it manually or open a new issue for HACS (can't help here as I don't use it).

**Comment by Aephir** [comment]
I tried creating an [issue in the HACS repo](https://github.com/hacs/integration/issues/1467), but they say that it's not a HACS issue.

I downloaded with HACS, and the `.../custom_components/bwalarm/resources/panel.html` shows 

```
var _VERSION = 'v1.12.6'
```

But not in the HA UI. I even tried opening the HA URL in a new browser that has never opened HA. 

I had to manually create the `config/resources` and copy the `bwalarm`. It's readable to everyone. I'm happy to help troubleshooting, but I have no idea where to start. Let me know if there's anything you can think of.

**Comment by akasma74** [comment]
Could you create a new issue and providing a clear description and all necessary information?

**Comment by lancelon** [comment]
I have this issue but it looks like I've somehow had two parallel installations of BWAlarm running for months and months. Suddenly today following a restart (for another issue) it's suddenly become a problem and broken. I've uninstalled and am now reinstalling.
