### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by Notpts** [akasma74/Hass-Custom-Alarm#108]
Hi,

I have installed with HACS and gives me this error:
"extra keys not allowed @ data['alarm_control_panel']"

"Log Detail ( ERROR )

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:326
Integration: Hass.io (documentation, issues)
First occurred: 14:33:16 (3 occurrences)
Last logged: 14:51:01
extra keys not allowed @ data['alarm_control_panel']"

Could you help please?
Thank you!

**Comment by akasma74** [comment]
First of all make sure you followed the [installation instructions](https://github.com/akasma74/Hass-Custom-Alarm#how-to-installation).
Please post here relevant part of your `configuration.yaml`

**Comment by akasma74** [comment]
I'm closing this issue because of no response.
Feel free to open a new one if you need.
