### ISSUE TITLE
Unable to view Key Pad on lovelace

### ISSUE THREAD

**Issue by impulsenz** [akasma74/Hass-Custom-Alarm#109]
Hey there First time posting an issue

I have an issue where the key pad is not showing up in the Lovelace card 

![image](https://user-images.githubusercontent.com/60640440/88000152-1696ea00-cb51-11ea-8ff6-61969813799f.png)

I wanted to add this in the front end and not just use the side pannel ( which is working fine)

Running the most up todate software on a Raspberry pi 3b+

**Comment by akasma74** [comment]
First of all, could you elaborate what exactly is wrong with the LL card?
Secondly, did you see a template with hints when you opened the issue?
Without that information I won't be able to help.

**Comment by akasma74** [comment]
I'm closing this issue because of no response.
Feel free to open a new one if you need.
