### ISSUE TITLE
Custom alarm won't work

### ISSUE THREAD

**Issue by bobvmierlo** [akasma74/Hass-Custom-Alarm#112]
**The component:**
 - Current version: v1.12.4
 - Last known working version (if any): None, first install

**Your setup:**
 - Home Assistant version: v0.113.1
 - Last known working Home Assistant version (if any):
 - OS: HassOS 4.11
 - Browser name & version: Chrome 84.0.4147.89

**Describe the bug**

Custom integration won't load.

```
This component is not working
Check the Home Assistant log for more details.
This integration: v1.12.4

Home Assistant: v0.113.1
```
The log doesn't show anything usefull to me though..

**To Reproduce**

**Expected behavior**

**Your bwalarm.yaml**

```yaml
platform: bwalarm
name: testalarm
```
**Home Assistant log**

```txt
Logger: frontend.js.latest.202007160
Source: components/system_log/__init__.py:209
First occurred: 6:43:25 PM (1 occurrences)
Last logged: 6:43:25 PM

https://MYHASURL/alarm:0:0 Uncaught
```
**Screenshots**

**Additional context**
<!-- Add any other context about the problem here.<!--

**Comment by bobvmierlo** [comment]
FYI, I installed through HACS

**Comment by akasma74** [comment]
So it's a first install and it doesn't work, right?

**Comment by bobvmierlo** [comment]
Yes sir, clean first install

**Comment by bobvmierlo** [comment]
Any idea how to get the integration working?

**Comment by akasma74** [comment]
Sorry, I know you opened it long time ago but I'm still not ready to give you the answer.
Need a) come up with a debugging idea and b) some spare time to deal with it.
Will come back to you as soon as my offline projects let me do that.

**Comment by bobvmierlo** [comment]
Any news on this yet?

**Comment by akasma74** [comment]
Yep. I have a [major problem](https://github.com/akasma74/Hass-Custom-Alarm/issues/124) that has much higher priority atm.
Still, I hope to deal with all open issues as soon as I can.

**Comment by bobvmierlo** [comment]
Went to use alarmo instead
