### ISSUE TITLE
Getting error message when check_before_arm: [] is in alarm.yaml

### ISSUE THREAD

**Issue by awshirley** [akasma74/Hass-Custom-Alarm#12]
**Your components (from Alarm/Settings/About):**
 - alarm component version v1.5
 - web panel v1.3.8_ak74
(I installed the latest code as of 6/20/19)

**Platform & Browser:**
 - Centos 7 Linux & Home assistant 0.94.4 (using Hassio and docker containers)
 - Browser Chrome 75.0.3770.100

**Describe the bug**
Error message in log when starting HomeAssistant

**To Reproduce**
1. Restart HomeAssistant 
2. Click on info
3. See Error Invalid config for [alarm_control_panel.bwalarm]:
4. Goto Alarm from side menu
5.  See error:
Home Alarm
This component is not working!
Invalid config for [alarm_control_panel.bwalarm]: [check_before_arm] is an invalid option for [alarm_control_panel.bwalarm]. Check: alarm_control_panel.bwalarm->states->armed_night->check_before_arm. (See /config/configuration.yaml, line 431). Please check the docs at https://home-assistant.io/components/alarm_control_panel.bwalarm/
(config.py)
Check the Home Assistant log for more details.
Home Assistant: v0.94.4
This Panel: v1.3.8_ak74

**Expected behavior**
Should not see this error

**Screenshots**
Invalid config for [alarm_control_panel.bwalarm]: [check_before_arm] is an invalid option for [alarm_control_panel.bwalarm]. Check: alarm_control_panel.bwalarm->states->armed_night->check_before_arm. (See /config/configuration.yaml, line 431). Please check the docs at https://home-assistant.io/components/alarm_control_panel.bwalarm/

**Additional context**
for the time being, I've had to comment out the check_before_arm: entry in alarm.yaml

**Comment by akasma74** [comment]
Could you tell me how did you upgrade and what you did to get this error (step by step)?
And can you post here your backed up alarm.yaml if you have one?
And the alarm.yaml with that check_before_arm entry?
If you have it, can you copy it in place of the current one (in /config folder), restart HA and confirm if the error appears again?

**Comment by akasma74** [comment]
should be fixed in 1.6.0b
can you check?

**Comment by awshirley** [comment]
I tried 1.6.0b.  Overwrote everything in the custom_components/bwalarm and alarm.yaml in the homeassistant folder.  It wouldn't let HA restart.  I had to put the old alarm.yaml back in (the one where I commented out check_before_arm).  After I did that, HA started and the alarm component appears to be working.



---- On Sun, 23 Jun 2019 16:51:42 -0500 akasma74 <notifications@github.com> wrote ----


should be fixed in 1.6.0b
 can you check?

**Comment by akasma74** [comment]
Can you check the latest release to see if it's resolved?

**Comment by awshirley** [comment]
Sure.  Have to do it later tonight.  On a family vacation. 

⁣Get BlueMail for Android ​

**Comment by awshirley** [comment]
I've got it installed and it's working.  Thanks for the help!



Andy Shirley


---- On Tue, 02 Jul 2019 11:16:33 -0500 akasma74 <notifications@github.com> wrote ----


Can you check the latest release to see if it's resolved?

**Comment by akasma74** [comment]
Hurray!
