### ISSUE TITLE
BW Alarm does not appear in the integration-menu of HA

### ISSUE THREAD

**Issue by GHToine** [akasma74/Hass-Custom-Alarm#126]
Running the latest version of Home Assistant: Home Assistant 0.116.4 on a PI4 model B 64bit and latest release of BWAlarm v1.12.7.

I did a manual installation:
After copying the folders and files from Github to the PI following the instructions and restarting HA (also tried 'reboot') and refreshing the cash of the browser (Chrome: 86.0.4240.75 (Officiële build) (64-bits) by typing Ctrl+F5, I still don't see the option 'bwalarm' in the integrations menu in HA.

I hope their is an solution. I also tried installing by HACS, but unfortunately I can't get HACS running (keeps loading), but HACS does show up in the integrations menu and BWAlarm is not.

I also edit configuration.yaml by adding "alarm_control_panel: !include resources/bwalarm/bwalarm.yaml"

_HA-log:
Logger: homeassistant.loader
Source: loader.py:440
First occurred: 9:56:50 (2 occurrences)
Last logged: 9:56:56

You are using a custom integration for bwalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant._

**Comment by akasma74** [comment]
Mate, this integration is not compatible with HA 0.115+ yet, I need to fix it.
See #124 for more details

**Comment by GHToine** [comment]
Thnx, I mist that.
