### ISSUE TITLE
I do not get the panel or access

### ISSUE THREAD

**Issue by robertogargon** [akasma74/Hass-Custom-Alarm#127]
I have installed according to indications the component both in manual and with HACS and the alarm does not appear in the browser. HA does not give me any error, I have given it a thousand laps but I am lost.
HA version is 0.115.6
 
Thank you

**Comment by akasma74** [comment]
The very first warning on the component's page says it's incompatible with 0.115 and higher.
It's still work in progress.
Duplicate #124
