### ISSUE TITLE
No version key

### ISSUE THREAD

**Issue by tomlut** [akasma74/Hass-Custom-Alarm#129]
**The component:**
 - Current version: 1.12.9
 - Last known working version (if any): 1.12.9

**Your setup:**
 - Home Assistant version: 2021.3.0
 - Last known working Home Assistant version (if any): 2021.2.x
 - OS: Windows
 - Browser name & version: Firefox 86.0

**Describe the bug**

As of Home Assistant 2021.3.0 custom integrations require a version key. See: https://github.com/home-assistant/core/pull/45919
**To Reproduce**

1. Start Home Assistant
2. Look in the log file

**Expected behavior**

**Your bwalarm.yaml**

```yaml
```
**Home Assistant log**

```txt
```
**Screenshots**

**Additional context**
<!-- Add any other context about the problem here.<!--

**Comment by tomlut** [comment]
I fixed this by appending:

```
"version": "0.0.0"
```

To the `manifest.json` file.

Don't forget the comma at the end of the line above.

**Comment by Tosko4** [comment]
@akasma74 by any chance got time to review this please?
