### ISSUE TITLE
HA beta 2021.12.0b1 breaks integration

### ISSUE THREAD

**Issue by jes1417** [akasma74/Hass-Custom-Alarm#136]
**The component:**
 - Current version: v1.12.11
 - Last known working version (if any): n/a

**Your setup:**
 - Home Assistant version: 2021.12.0b1
 - Last known working Home Assistant version (if any): 2021.11.XX
 - OS: Docker
 - Browser name & version: n/a

**Describe the bug**

New beta breaks the integration and will not start, also cannot reboot HA after upgrade due to errors

**To Reproduce**

**Expected behavior**

**Your bwalarm.yaml**

```yaml
```
**Home Assistant log**

```
This error originated from a custom integration.

Logger: homeassistant.config
Source: custom_components/bwalarm/alarm_control_panel.py:54
Integration: bwalarm (documentation)
First occurred: 12:41:28 AM (1 occurrences)
Last logged: 12:41:28 AM

Platform error: alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 887, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 54, in <module>
    from homeassistant.util          import sanitize_path
ImportError: cannot import name 'sanitize_path' from 'homeassistant.util' (/usr/src/homeassistant/homeassistant/util/__init__.py)
```

```
Logger: homeassistant.components.homeassistant
Source: components/homeassistant/__init__.py:160
Integration: Home Assistant Core Integration (documentation, issues)
First occurred: 1:14:58 AM (1 occurrences)
Last logged: 1:14:58 AM

The system cannot restart because the configuration is not valid: Platform error alarm_control_panel.bwalarm - cannot import name 'sanitize_path' from 'homeassistant.util' (/usr/src/homeassistant/homeassistant/util/__init__.py)
```

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/homeassistant/__init__.py:170
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:14:58 AM (1 occurrences)
Last logged: 1:14:58 AM

[140364263012672] The system cannot restart because the configuration is not valid: Platform error alarm_control_panel.bwalarm - cannot import name 'sanitize_path' from 'homeassistant.util' (/usr/src/homeassistant/homeassistant/util/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 733, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 170, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error alarm_control_panel.bwalarm - cannot import name 'sanitize_path' from 'homeassistant.util' (/usr/src/homeassistant/homeassistant/util/__init__.py)
```
**Screenshots**

**Additional context**
<!-- Add any other context about the problem here.<!--

**Comment by guyyar89** [comment]
how to fix it?

**Comment by skynet01** [comment]
Anu updates on this? Looks like it might be a fairly simple issue with sanitizing a path name?

**Comment by phithor** [comment]
Should be super simple fix

https://www.home-assistant.io/blog/2021/12/11/release-202112/#breaking-changes

https://github.com/home-assistant/core/pull/60859

Please fix ser

**Comment by mperone** [comment]
Any updates?

**Comment by skynet01** [comment]
Not sure if he will reply as it's been more then a week since this got reported... I just ended up migrating to [Alarmo](https://github.com/nielsfaber/alarmo) it uses almost all the same state names so all my automations continued to work. (You just have to switch pending and arming)

**Comment by v966732** [comment]
I've managed to bodge a fix for this issue until we the component gets a proper update.  I've tested this and it works for me with both 2021.11 and 2021.12 HA releases but please make sure you backup any files and test it yourself.

The file that changes is the alarm_control_panel.py file located in the /custom_components/bwalarm folder.  I've attached it zipped to this post.

Hope this helps.

[alarm_control_panel.zip](https://github.com/akasma74/Hass-Custom-Alarm/files/7711411/alarm_control_panel.zip)

**Comment by guyyar89** [comment]
thanks its work!
> I've managed to bodge a fix for this issue until the component gets a proper update. I've tested this and it works for me with both 2021.11 and 2021.12 HA releases but please make sure you backup any files and test it yourself.
> 
> The file that changes is the alarm_control_panel.py file located in the /custom_components/bwalarm folder. I've attached it zipped to this post.
> 
> Hope this helps.
> 
> [alarm_control_panel.zip](https://github.com/akasma74/Hass-Custom-Alarm/files/7711411/alarm_control_panel.zip)

**Comment by jes1417** [comment]
> I've managed to bodge a fix for this issue until the component gets a proper update.  I've tested this and it works for me with both 2021.11 and 2021.12 HA releases but please make sure you backup any files and test it yourself.
> 
> The file that changes is the alarm_control_panel.py file located in the /custom_components/bwalarm folder.  I've attached it zipped to this post.
> 
> Hope this helps.
> 
> [alarm_control_panel.zip](https://github.com/akasma74/Hass-Custom-Alarm/files/7711411/alarm_control_panel.zip)
> 
> 

Can you submit a PR to get your fix merged?

**Comment by v966732** [comment]
PR Submitted to fix this issue - https://github.com/akasma74/Hass-Custom-Alarm/pull/137

**Comment by akasma74** [comment]
Sorry for the delay guys, was way too  busy and almost missed that email.
The recent release should fix this easily but feel free to reopen it if it doesn't.

Thanks for your help.
