### ISSUE TITLE
Deprecated call

### ISSUE THREAD

**Issue by e2m32** [akasma74/Hass-Custom-Alarm#138]
**The component:**
 - Current version: 2021.12.10
 - Last known working version (if any): 2021.11.0

**Your setup:**
 - Home Assistant version: 2021.12.10
 - Last known working Home Assistant version (if any): 2021.11.0
 - OS: Home Assistant OS
 - Browser name & version: Chrome

**Describe the bug**
WARNING in logs from Home Assistant:
```
Entity alarm_control_panel.house (<class 'custom_components.bwalarm.alarm_control_panel.BWAlarm'>) implements device_state_attributes. Please report it to the custom component author.
```

Everything is working right now, but not sure when HA will deprecate this service call and break the component.

**Comment by akasma74** [comment]
Thanks for reporting that.
It's the result of [this PR](https://github.com/home-assistant/core/pull/47304).
Will sort it out shortly as it's a simple change of name.

**Comment by akasma74** [comment]
Should work now if you update to 1.12.13
