### ISSUE TITLE
Python 3.10 dependency conflict

### ISSUE THREAD

**Issue by LouPaloma** [akasma74/Hass-Custom-Alarm#140]
More of a heads-up than a bug:  With impending 3.10 python requirement there looks to be an incompatibility with the current HACS released version (1.12.14) and Python 3.10.

The dependency on `ruamel.yaml==0.15.100` cannot be satisfied and will need to be updated to 0.17+

**Comment by akasma74** [comment]
Thanks make, I'll have a look into it soon.

**Comment by akasma74** [comment]
@LouPaloma could you please check that the changes I made don't break anything and (possibly) satisfy upcoming requirements?

**Comment by LouPaloma** [comment]
I can confirm that the change in `manifest.json` works with python 3.9, but will have to wait until the weekend to test with 3.10 environment

**Comment by akasma74** [comment]
@LouPaloma cool, thanks.
please keep me updated so I make a new release if everything works well with the change.

**Comment by alitaker** [comment]
Alarm panel works for me on Python 3.10, HA 2023.1.1 and 
```ruamel.yaml==0.17.21```

**Comment by akasma74** [comment]
@alitaker thanks for confirming.
I'm surprised people still using it in such a state.. 
Anyway, looks like it's time to create a new release.

**Comment by alitaker** [comment]
>  I'm surprised people still using it in such a state.. 

Unfortunately I have no time to look at the alternatives :blush:
