### ISSUE TITLE
cts 700

### ISSUE THREAD

**Issue by Ronrico2** [akasma74/Hass-Custom-Alarm#142]
hello. Was it possible to get this integration to work with the cts 700 on a  nilan compact p air 9???

**Comment by akasma74** [comment]
Sorry, I don't know what cts 700 is.
Have you checked the [documentation](https://github.com/akasma74/Hass-Custom-Alarm/blob/master/custom_components/bwalarm/resources/doc/configuration.md)? It's pretty straightforward..
If you have any questions about configuration, feel free to ask for help in the [forum](https://community.home-assistant.io/t/bwalarm-akasma74-edition/113666).
I'll close this issue for now as it's more like a question.
