### ISSUE TITLE
async_alarm_arm_away() missing 1 required positional argument: 'ignore_open_sensors'

### ISSUE THREAD

**Issue by asifma** [akasma74/Hass-Custom-Alarm#17]
I cant call Arm_away with the service call.

I try to use the "ignore_open_sensors" parameter, but it does not work:

{
"entity_id": "alarm_control_panel.house",
"code":"0000",
"ignore_open_sensors": true
}

I get:
extra keys not allowed @ data['ignore_open_sensors']

If i don't use it, I instead get:

async_alarm_arm_away() missing 1 required positional argument: 'ignore_open_sensors'

Am I doing something wrong here?

**Comment by akasma74** [comment]
Could you edit the issue to make it a proper one?
Without having all relevant details I can't help you.

**Comment by asifma** [comment]
I used the wrong service. Saw a new service called: bwalarm.alarm_arm_away

Thanks! And sorry for not reporting the issue with the correct format.
