### ISSUE TITLE
Unable to select sensors

### ISSUE THREAD

**Issue by benmprojects** [akasma74/Hass-Custom-Alarm#2]
**Describe the bug**
I have a problem where on the sensors page when I select a sensor it ticks it then unticks it. All other setting seem to save ok.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Alarm' then login in to admin
2. Click on 'sensors'
3. then tick a sensor
4. See the sensor you have ticked untick.

**Expected behaviour**
Sensor should be selected and saved.

**Browser (please complete the following information):**
 - Browser Chrome Version 73.0.3683.103 (Official Build) (64-bit)
 - Mac OS High Sierra

**Comment by akasma74** [comment]
Could you post your versions of bawlarm and this panel (can find them at the bottom of Settings/About page)?

To be honest, I cannot reproduce it with the very same version of Chrome on El Capitan..
Have you tried another browser (Safari/Firefox)?

**Comment by benmprojects** [comment]
Sorry to waste your time but after clearing my cache from both browsers I was testing everything appears to be working.
