### ISSUE TITLE
MQTT set default for "ignore_open_sensors"

### ISSUE THREAD

**Issue by e2m32** [akasma74/Hass-Custom-Alarm#25]
**Is your feature request related to a problem? Please describe.**
I use Thanks, Mister!'s MQTT Alarm Panel app on a phone mounted on the exit of my house. If I have the door open, then it won't arm... and there is no indication that it's not going to arm.

**Describe the solution you'd like**
I understand the desire to make 'ignore_open_sensors' set to False as default as it could be a security issue, but it would be convenient to be able to override the default in the UI. 

**Describe alternatives you've considered**
In the UI add an option to set 'ignore_open_sensors':True

**Additional context**
I was able to change the default value by doing a code edit for others that may come across this issue. Line 342 in alarm_control_panel.py from `CONST_DEF_IGNORE_OPEN_SENSORS   =   False` to `CONST_DEF_IGNORE_OPEN_SENSORS   =   True`

**Comment by akasma74** [comment]
> **Is your feature request related to a problem? Please describe.**
> I use Thanks, Mister!'s MQTT Alarm Panel app on a phone mounted on the exit of my house. If I have the door open, then it won't arm... and there is no indication that it's not going to arm.

So you'd leave your house with an open door? ;)

Actually, there is an indication as you can check either your integration's state OR its state topic.

Of course, it's possible to make default value of  `ignore_open_sensors` configurable, but what about going the same way as I went for service calls, i.e having ARM_XXX commands that set alarm unconditionally and SAFE_ARM_XXX that do it only with clear sensors?
These command names will be configurable as they are now and it will let user define that ARM_AWAY sets alarm with clean sensors, for example.

What do you think?
