### ISSUE TITLE
Not showing up in HACS

### ISSUE THREAD

**Issue by awshirley** [akasma74/Hass-Custom-Alarm#30]
**Your components (from Alarm/Settings/About):**
 - component version v1.8.0b

**Platform & Browser:**
 - Platform name & Home assistant version Hass.io 0.95.4
 - Chrome 75.0.3770.100

**Describe the bug**
The alarm doesn't show in the HACS Store

**To Reproduce**
1. Go to Community on side menu
2. Click on store
3. Scroll down to find Fork of Yet another take on alarm
4.  It's not there.

**Expected behavior**
Expect to find Fork of Yet another take on alarm on HACS store

**Screenshots**

**Comment by akasma74** [comment]
Do you really think it's a valid issue?

**Comment by awshirley** [comment]
Wasn't sure where to start with Hass-Custom-Alarm or HACS.


---- On Thu, 11 Jul 2019 01:37:53 -0500 akasma74 <notifications@github.com> wrote ----


Do you really think it's a valid issue?

**Comment by akasma74** [comment]
2 reasons:
1. I have no control over the update process of this integration, it's up to users
2. Lack of important information.

I installed it twice and it worked both times..
