### ISSUE TITLE
MQTT response for Valid or Invalid alarm codes

### ISSUE THREAD

**Issue by benmprojects** [akasma74/Hass-Custom-Alarm#32]
**Is your feature request related to a problem? Please describe.**
I think it would be useful for people using mqtt commands to arm and disarm if it be possible to add a command to be sent via MQTT on successful code for arming and disarming

**Describe the solution you'd like**
In the MQTT section of the backend add a couple of textboxes similar to the commands text boxes for a mqtt command to be sent on valid code and invalid code e.g.

Vaild code received MQTT command to send:
______________________________________
hasp/alarm01/command/beepvalid
______________________________________

Invaild code received MQTT command to send:
______________________________________
hasp/alarm01/command/beepinvalid
______________________________________

This would allow some feedback on devices if the code is correct. In the example above my HA switchplate has a piezo buzzer installed. If the command above is received it beeps. (I have submitted a pull request to HA switchplate github with the required code for the beeps.)

**Describe alternatives you've considered**
None

**Comment by benmprojects** [comment]
I have managed to do this with automation's. You can can't this feature request if you like.
Automation below if anyone would like it. (HA Switch Plate)

  - alias: hasp_alarm_p7_InvalidCode
    trigger:
    - platform: mqtt
      topic: 'hasp/alarm01/state/p[7].b[15]'
      payload: 'OFF'
    action:
    - delay:
        seconds: 0.5
    - condition: state
      entity_id: alarm_control_panel.house
      state: 'disarmed'
    - service: mqtt.publish
      data:
        topic: 'hasp/alarm01/command/beep'

**Comment by akasma74** [comment]
Yeah, you can easily do that with automation as the alarm's state is in both mqtt topic and accessible via HA - send ARM command, wait for say, 3 seconds, and if the state is still disarmed, do something.. will it do the job?

**Comment by benmprojects** [comment]
Yes seem to work well. Spent ages looking at the code then thought about automations!!

Thanks

On 12 Jul. 2019 6:02 pm, akasma74 <notifications@github.com> wrote:

Yeah, you can easily do that with automation as the alarm's state is in both mqtt topic and accessible via HA - send ARM command, wait for say, 3 seconds, and if the state is still disarmed, do something.. will it do the job?

**Comment by akasma74** [comment]
Ok, that's great
