### ISSUE TITLE
Alarm Settings

### ISSUE THREAD

**Issue by darinhagan** [akasma74/Hass-Custom-Alarm#33]
When I restart HA, the bwalarm.yaml file is set to default.  I have cleared my browser cache and tried different browsers.  Please help.

**Comment by akasma74** [comment]
Could you add necessary details to your issue and describe it properly to make it valid?
Otherwise it's impossible to help.

**Comment by darinhagan** [comment]
This integration: v1.10.1
Home Assistant: v0.95.4
Python: v(3,7,3,final,0)

Details:
#1 Modifications in the settings panel via the GUI are lost after restarting Home Assistant.
     - ex: settings>design>alarm panel title, will revert back to the default title "Home Alarm"

Conclusion:
Corrupt installation.

Solution:
Uninstall and reinstall of Home Assistant.

I correct the challenge.  You may close this request.
