### ISSUE TITLE
Broken Page

### ISSUE THREAD

**Issue by marrobHD** [akasma74/Hass-Custom-Alarm#35]
**Your components (from Alarm/Settings/About):**
 - v1.10.1

**Platform & Browser:**
 - Platform name & Home assistant version [e.g. Hass.io 0.96.4]
 - Browser name & version

**Describe the bug**
The Alarm page isnt displayed right

**To Reproduce**
1. Go to 'the Alarm Panel Page'

**Expected behavior**
--

**Screenshots**
http://n8970q34vnvidunh897qfc5wenh87v.tk/s/rtR6R4krGFSRe6C/preview

**Additional context**
....

**Comment by akasma74** [comment]
Could you add the necessary information to your issue as currently it's incomplete and I'm unable to help?
From the screenshot I can see that you use a pretty old version of the integrating so I'd suggest to update.

**Comment by marrobHD** [comment]
No have used master

**Comment by akasma74** [comment]
again, there is no such thing as 'master' and I need exact versions to be in a position to help.
so please edit your original post to add all necessary information

**Comment by marrobHD** [comment]
v1.10.1

**Comment by marrobHD** [comment]
Your Versions:

Home Assistant: v0.96.5

This Panel: v1.3.6_ak74

Component (Bwalarm): v

Python: v(3,7,4,final,0)

It wont detect the bwalarm version

**Comment by marrobHD** [comment]
I still had a panel folder in the config directory. It was from an old version. I deleted it, removed the panel_custom entry from the configuration.yaml, reloaded the page and now everything works.
