### ISSUE TITLE
Overwriting Integration warning

### ISSUE THREAD

**Issue by djtommye** [akasma74/Hass-Custom-Alarm#36]
**Your components (from Alarm/Settings/About):**
 - component version [e.g v1.5.0]

**Platform & Browser:**
 - Platform name & Home assistant version [e.g. Hass.io 0.91.0]
 - Browser name & version

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by akasma74** [comment]
I'm closing the issue as it's empty. Feel free to open a proper one.

**Comment by djtommye** [comment]
I have no idea why this was empty.  So sorry!  I'll open a complete request.
