### ISSUE TITLE
Overwriting alarm

### ISSUE THREAD

**Issue by djtommye** [akasma74/Hass-Custom-Alarm#39]
Your components (from Alarm/Settings/About):

    Home Assistant: v0.96.4
    This Panel: v1.3.6
    Component (Bwalarm): vk74 edition v 1.10.1
    Python: v(3,7,4,final,0)

Platform & Browser:

    hassio
    HassOS 2.12
    production
    Firefox 68.0.1 64bit

Describe the bug
When hass boots, I get an error "Overwriting integration alarm" in the log

To Reproduce
- Restart hass
- check the log

Expected behavior
- no warning or better explanation

![overwriting](https://user-images.githubusercontent.com/24887617/62134316-e1d9b500-b2a5-11e9-91cc-d04a715acb68.PNG)

**Comment by akasma74** [comment]
The current version of this integration is v1.10.1 and there is no separate "This Panel" version so you are running an old version.

I'd suggest to update the integration [as described](https://github.com/akasma74/Hass-Custom-Alarm#how-to-update) and make sure you followed [instructions](https://github.com/akasma74/Hass-Custom-Alarm#after-update-for-all-methods) properly.
In your case it seems like you need to clear the cache.

**Comment by akasma74** [comment]
I'm closing this issue because of no answer.
