### ISSUE TITLE
Keypad not shown in Lovelace (Wanting to Arm the Alarm with Pin)

### ISSUE THREAD

**Issue by YoinkZed** [akasma74/Hass-Custom-Alarm#40]
**Your components (from Alarm/Settings/About):**
This integration: v1.10.1
Home Assistant: v0.96.4
Python: v(3,7,4,final,0)

**Platform & Browser:**
 - Hassio & Home assistant version [ Hass.io 0.96.4 ]
 - Google Chrome Version 75.0.3770.142 (Officiel version) (64-bit)

**Describe the bug**
When setting the option in Alarm --> Settings --> Alarm: Require a passcode to set the alarm, I'm not being presented to a keypad on my  Lovelace Alarm Card, when I want to Arm my Alarm.
The only way I can get a keypad shown, is if I arm the alarm through the Alarm Menu and when armed, a keypad is then shown to disarm my alarm.

**To Reproduce**
1. Add Alarm-Card to Lovelace
2. Then it doesn't get shown

**Expected behavior**
I expected the Alarm Card to show a Keypad, due to the setting set in the settings of the Alarm:
Alarm --> Settings --> Alarm: Require a passcode to set the alarm

**Screenshots**
Lovelace Alarm Card:
![image](https://user-images.githubusercontent.com/35101650/62142582-e080aa80-b2ee-11e9-8506-2e3ab4ad2514.png)

Alarm Settings:
![image](https://user-images.githubusercontent.com/35101650/62142647-fdb57900-b2ee-11e9-88bf-b3255c9a1c05.png)

**Additional context**
This was working with the old Gazoscalvertos version on the same version with Hassio 0.96.4.
I upgraded to this Custom Component following the guide today (once again), and then upgraded it using HACS.
Everything else is working with the Alarm.

**Comment by YoinkZed** [comment]
I just saw your latest post on the community - so do you want me to delete this and create it as a Feature Request instead?

**Comment by akasma74** [comment]
No, just leave it as it is

**Comment by michaelhdmd** [comment]
I am using Lovelace as well, but I have an "iframe" card and point to the BWAlarm URL.  I had to use the hard coded IP, rather than the "http://hassio.local:8123/alarm".  There are some CSS issues and I have not kept up with recent updates from akasma74, but it works great for me.

**Comment by akasma74** [comment]
> I am using Lovelace as well, but I have an "iframe" card and point to the BWAlarm URL. I had to use the hard coded IP, rather than the "http://hassio.local:8123/alarm". There are some CSS issues and I have not kept up with recent updates from akasma74, but it works great for me.

do you mean you're using the original bwalarm or just that your version of this integration isn't the latest release?
regarding your comment, as it's NOT a Lovelace card but a wrapper around the Alarm view, I'm not surprised that it works.
it could do as a workaround for some..

**Comment by michaelhdmd** [comment]
I am using the BWAlarm branch, but I have not updated since the spring.  Correct, I am not using the Lovelace Alarm card or a custom card.  Just an iFrame card to display the BWAlarm URL.  I do the same for Windy Weather and www.clocktab.com.

**Comment by ezraholm50** [comment]
I've moved from the old repo with all the summed up fixes (manually) to this repo on HACS and that broke my alarm panel for the lovelace frontend. Been seeing more and more people having this issue.

**Comment by akasma74** [comment]
it cannot break your alarm panel
