### ISSUE TITLE
Incorrect event message "Alarm has been tripped by undefined"

### ISSUE THREAD

**Issue by remygiraud** [akasma74/Hass-Custom-Alarm#41]
When I am using an API call to change the state of a sensor and if the new state of this sensor triggers the alarm, the event shown on the log page is:
`Alarm has been tripped by undefined
`
So the entity_id of the sensor responsible is not listed.
Thanks!

**Comment by akasma74** [comment]
I need more details to be able to reproduce the issue, i.e what API call you use etc.

**Comment by remygiraud** [comment]
The API call:
`http://192.168.x.y:8123/api/states/sensor.eye_presence`

and I POST:

`{"state": on}`

With the sensor being defined as: 
`sensor:
  - platform: template
    sensors:
         eye_presence:
              friendly_name: "Eye Presence"
             value_template: "{{ value }}"`

I am moving from my old home automation system to HA. I am using this to transfer sensors from the old system to the new one.

**Comment by akasma74** [comment]
And HOW do you POST?

**Comment by remygiraud** [comment]
Either using "postman" in chrome or http node in nodered. Both give the same result.

**Comment by akasma74** [comment]
Well, I can't test it then because I have no NodeRed and "postman" in chrome is deprecated.. any ideas?

**Comment by akasma74** [comment]
I'm closing this issue now because there was no response. Feel free to reopen it or create a new one if you need.
