### ISSUE TITLE
Make fingerprint icon optional in theme

### ISSUE THREAD

**Issue by jcooper-korg** [akasma74/Hass-Custom-Alarm#42]
The fingerprint icon in the portrait view (as seen on an iPhone) is not very attractive, and potentially confusing (implies you can use the fingerprint sensor on the iPhone). 
I'd prefer this just say "disarm".  
Can we make it optional in the theme?

**Comment by akasma74** [comment]
The idea behind it is to fit everything on a narrow screen, hence the C instead of Cancel.
What should we use instead of Disarm as it's a bit too long?

**Comment by jcooper-korg** [comment]
Seems like there's plenty of room to just make the buttons wider and use the words "Clear" and "Disarm":
![IMG_4119](https://user-images.githubusercontent.com/1987267/62840240-28d38d00-bc4c-11e9-87a7-91db7abd2915.PNG)

**Comment by akasma74** [comment]
Ok, I'll give it a try.

Actually, you can play with it for yourself locally and tell us what works best.
Just make the following changes to resources/panel.html:

line 192: replace C with Clear, i.e
```HTML
<mwc-button class='clear action-button' on-click='callclearcode' raised>Clear</mwc-button>
```
and line 195: you need a button here as well, not an icon
```HTML
<mwc-button class='action-button disarm' on-click='callAlarmService' data-call='disarm' raised>Disarm</mwc-button>
```

**Comment by jcooper-korg** [comment]
implemented in commit 6010c336. 
![IMG_4137](https://user-images.githubusercontent.com/1987267/62995737-c5498b00-be16-11e9-825b-3e5aece088a8.PNG)

I also modified the sm (tablet width > 1024) view to have the same button groupings with 0 at bottom center:
![Screen Shot 2019-08-13 at 10 09 16 PM](https://user-images.githubusercontent.com/1987267/62995808-1a859c80-be17-11e9-8ff5-1d9ebc20b2ba.png)

I'm still experimenting with increasing the button sizes in the sm tablet view.

**Comment by jcooper-korg** [comment]
not sure if these changes are desirable for everyone. i can send a pull request if you think so.

**Comment by akasma74** [comment]
let me think about it as there's no rush.. ;)

**Comment by necromn** [comment]
I think the disarm button is far and away more logic for mot people. I have the same problem with people not knowing how to use it - though less critical because mostly arm/disarm through presence automations.
