### ISSUE TITLE
Shouldn't allow access to Activity Log in armed screen

### ISSUE THREAD

**Issue by jcooper-korg** [akasma74/Hass-Custom-Alarm#44]
Seems like the activity log should be hidden when the system is armed. (Nothing should be available but the keypad when armed. If a thief enters the house, they shouldn't have any access)

**Comment by akasma74** [comment]
I'm pretty sure it's hidden when alarm set.
Could you provide all necessary data to reproduce the issue, including versions and steps?

**Comment by jcooper-korg** [comment]
Enable the Log in the Alarm settings.
Arm the alarm.
See the log button at bottom of the screen:
![IMG_4137](https://user-images.githubusercontent.com/1987267/62996040-0db57880-be18-11e9-80c5-f3a9cf1028f1.PNG)

**Comment by akasma74** [comment]
what's your integration's version and do you see the same set of icons at the bottom of your screen on different devices/in different browsers?

**Comment by jcooper-korg** [comment]
I'm at the head of bwalarm, and Home Assistant v0.96.5
It's same across all browsers/devices.
