### ISSUE TITLE
"Hide HA Sidebar When Armed" does not hide

### ISSUE THREAD

**Issue by TJPoorman** [akasma74/Hass-Custom-Alarm#48]
**Your components (from Alarm/Settings/About):**
 - v1.10.2

**Platform & Browser:**
 - Hass.io running in Docker on Ubuntu v0.96.2
 - Firefox 68.0.2 (64-bit)
   Chrome 76.0.3809.100 (64-bit)

**Describe the bug**
Enabling "Hide HA Sidebar When Armed" has no effect on the sidebar.  Attempted with all arming states with and without collapsing the sidebar

**Expected behavior**
"Hide HA Sidebar When Armed" should hide the sidebar element when enabled.

**Additional context**
Nothing showing in error logs in Home Assistant or Firefox or Chrome

**Comment by akasma74** [comment]
Have a look at the [first paragraph](https://community.home-assistant.io/t/bwalarm-akasma74-edition/113666/361)

**Comment by TJPoorman** [comment]
Okay that worked.  It may be worth noting that this option was not available in HA v96.2 (Not available until 96.3).  After updating all is working as expected.

**Comment by akasma74** [comment]
> Okay that worked. It may be worth noting that this option was not available in HA v96.2 (Not available until 96.3). After updating all is working as expected.

feel free to create a PR to the [configuration.md](https://github.com/akasma74/Hass-Custom-Alarm/blob/master/custom_components/bwalarm/resources/doc/configuration.md) file, I'd really appreciate it
