### ISSUE TITLE
MQTT Disarm with passcode

### ISSUE THREAD

**Issue by benmprojects** [akasma74/Hass-Custom-Alarm#5]
**Is your feature request related to a problem? Please describe.**
Allow Disarm/Arm via MQTT with the passcode in the payload. This will allow the use of the Android Alarm Panel.

**Describe the solution you'd like**
As above

**Comment by manznOnly** [comment]
use these code works to enable mqtt from @Tyre88 (with override function)

https://github.com/gazoscalvertos/Hass-Custom-Alarm/pull/65/commits/3f9fd9e54d4ae740482ee178227c4a0c334fc83a

**Comment by akasma74** [comment]
@benmprojects, it's already supports Disarm with passcode.
Could you provide more info regarding your request, i.e a sample message to arm/disarm that Android Alarm Panel sends (by the way, what is it?)

@manznOnly I'm not sure the PR you're referring to is the right one in this case - to me it looks strange as `_override_code` flag is only applicable to Disarm functionality, but he uses it in ARM_xxx as well..

**Comment by akasma74** [comment]
OK, to sum the things up:
The MQTT Alarm Control Panel does not send anything apart from the command itself in payload, i.e it's ARM_AWAY, ARM_HOME or DISARM. I could not find any options to include codes in payload.
The alarm component works fine with that control panel, you just need to enable Disarm Without Passcode in MQTT settings.

I'm closing the FR.
Feel free to open a new one, just provide enough info to avoid any guesswork as only you know what you're asking for.
