### ISSUE TITLE
bwalarm not working after upgraded to 0.100.0

### ISSUE THREAD

**Issue by boracay504** [akasma74/Hass-Custom-Alarm#51]
**Your components (from Alarm/Settings/About):**
 - component version v1.10.2

**Platform & Browser:**
 - Platform name & Home assistant version : Hass.io 0.100.0
 - Browser name & version: Chrome Version 77.0.3865.120 (Official Build) (64-bit)

**Describe the bug**
The following components and platforms could not be set up:
alarm-control-panel.bwalarm

Entity not available: alarm_control_panel.house

tried to restart the HA but problem still persist. It was working before and just after the upgrade it started not able to recognize.

**Comment by akasma74** [comment]
Could you add the relevant portion of HA log output to the issue description?
There might be some clue..

**Comment by akasma74** [comment]
OK, it's fixed in the [latest release](https://github.com/akasma74/Hass-Custom-Alarm/releases/tag/v1.10.3)
