### ISSUE TITLE
Lost configuration switches

### ISSUE THREAD

**Issue by tech165** [akasma74/Hass-Custom-Alarm#52]
**Your components (from Alarm/Settings/About):**
v1.10.2

**Platform & Browser:**
Hass.Io Docker v0.100.1
Safari 13.0.2, Chrome 77.0.3865.120 and Firefox 63.0.3

**Describe the bug**
In configurator all switches are missing.

**To Reproduce**
Open configuration panel and chose any settings with a toggle switch, the switch won't be visible.

**Expected behavior**
Switch there

Screenshot : 

<img width="1053" alt="screenshot" src="https://user-images.githubusercontent.com/22420251/66773228-95f1e180-ee8c-11e9-886c-5e6ac588647e.png">

Look as all polymer paper-toggle-button are not showing ...

**Comment by tech165** [comment]
Looks related to : Switch paper-toggle-button to mwc-switch [https://github.com/home-assistant/home-assistant-polymer/pull/3683](url)

**Comment by tech165** [comment]
Created a pull request ... would need to test for pre 0.100 user but working great on 0.101

**Comment by tech165** [comment]
From what I understand they pulled completely paper-toggle-button from their package.json ...

**Comment by akasma74** [comment]
Yeah.. fixed in [v1.10.3](https://github.com/akasma74/Hass-Custom-Alarm/releases/tag/v1.10.3)
