### ISSUE TITLE
Ruamel attempt to install on boot

### ISSUE THREAD

**Issue by riddik14** [akasma74/Hass-Custom-Alarm#56]
why on boot of hassio there is "Attempting install of ruamel.yaml==0.15.42", is a bug or is normal?

**Comment by riddik14** [comment]
perché all'avvio di hassio c'è "Tentare di installare ruamel.yaml == 0.15.42", è un bug o è normale?

**Comment by akasma74** [comment]
English here please.
Yes, it is normal but it should only happen once and should not repeat on every HA start.

**Comment by SPCulhane** [comment]
@akasma74 this happening on my hass.io install and I have to manually install it because a higher version is already installed. If I don't manually install it, reboots take a long time (they have to timeout trying to install ruamel.yaml==0.15.42). Any ideas?

**Comment by akasma74** [comment]
@SPCulhane what is your  HA version?

**Comment by SPCulhane** [comment]
i followed you suggestion and it worked

**Comment by akasma74** [comment]
ok, great.
I'll release a version with this fix soon.
