### ISSUE TITLE
BWalarm Broken in HA 0.103

### ISSUE THREAD

**Issue by aidbish** [akasma74/Hass-Custom-Alarm#60]
**Your components (from Alarm/Settings/About):**
This integration: v1.11.0

**Platform & Browser:**
 - Docker Hass 0.103.0b0
 - Edge Dev 80.0.345.0

**Describe the bug**
BWALARM is broken with lastest beta. Release notes indicate changes to alarm_alarm_panel
https://rc.home-assistant.io/blog/2019/12/04/release-103/

**To Reproduce**
Upgrade to latest beta

**Expected behavior**
Alarm system should function on latest beta

**Additional context**
2019-12-05 12:33:01 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up platform bwalarm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 425, in async_setup_platform
    alarm = BWAlarm(hass, config, mqtt)
TypeError: Can't instantiate abstract class BWAlarm with abstract methods supported_features

**Comment by akasma74** [comment]
Perhap's because it's a beta, right?
Anyway, I cannot support something that is not documented and even announced ;)

**Comment by aidbish** [comment]
Well its released in a week, i will check next beta when released.
Just thought i would give you the heads up

**Comment by akasma74** [comment]
Thanks for that, will keep an eye on release notes and check the new release out.
Peace ;)

**Comment by Tosko4** [comment]
It has been released, installed it and I can confirm it no longer works:

This component is not working
Error while setting up platform bwalarm
custom_components/bwalarm/alarm_control_panel.py (ERROR) (custom_components/bwalarm/alarm_control_panel.py)
Check the Home Assistant log for more details.
This integration: v1.11.0

Home Assistant: v0.103.0

**Comment by akasma74** [comment]
I know it's not workong. Looking into it right now.
If it's exactly what I think it is, HA boys didn't even put it in "breaking changes".. :\

**Comment by Tosko4** [comment]
@akasma74 please! I just installed this module. Made sure i checked breaking changed before upgrading. Hope you can fix it T_T

**Comment by akasma74** [comment]
I believe you can reverse your upgrade i.e upgrade to 0.102.3 ;) until I fix it

**Comment by Buster1959** [comment]
I had this so for now I have rolled back: from the CommandLine "ha update --version=0.102.3" without the quotes.
