### ISSUE TITLE
Alarm Panel not setting ZWave Devices

### ISSUE THREAD

**Issue by Buster1959** [akasma74/Hass-Custom-Alarm#61]
This integration: v1.11.0
Home Assistant: v0.102.3
Chrome - Version 78.0.3904.108 (Official Build) (64-bit)

When setting Arm from the Alarm Panel via Away none of the Motion Sensors or Door Sensors are set to Armed.

I have checked that the sensors are selected both in the UI and also within the alarm.yaml.

Only clear message is from the logs:
https://[myURL]/frontend_latest/chunk.d5961ced1d8380ae21ba.js:2417:193320 Uncaught YAMLException: unacceptable kind of an object to dump [object Undefined]
Connection lost. Reconnecting…

Any pointers please?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by akasma74** [comment]
I need to see your `bwalarm.yaml` because I don't understand how the alarm can "set" sensors or devices - they just send their signals and the alarm triggers if it's in Armed state and receives such signal.
Is it a clear install or you've upgraded the integration?
Are you using a separate alarm panel (`Alarm` from the sidebar) to Arm Away?

**Comment by Buster1959** [comment]
Thank you for looking at this: 

Below is the Alarm.yaml I have where I have replaced sensitive information with []

Also I am still getting:

Not passing an entity ID to a service to target all entities is deprecated. Update your call to alarm_control_panel.alarm_arm_away to be instead: entity_id: all
 
Alarm.yaml
`##########################################################
## CUSTOM ALARM COMPONENT ALARM.YAML
## https://github.com/gazoscalvertos/Hass-Custom-Alarm
## VERSION:  1.0.2
## MODIFIED: 18/04/18
## CHANGE LOG:
## Add Multi Codes, names, pics
## optional code to arm alarm
## Default Interface password: HG28!!&dn
##########################################################

platform: bwalarm
name: House
panel:
  camera_update_interval: ''
  cameras: []
  enable_camera_panel: 'False'
  enable_clock: 'True'
  enable_clock_12hr: 'False'
  enable_custom_panel: 'False'
  enable_floorplan_panel: 'False'
  enable_sensors_panel: 'True'
  enable_serif_font: 'True'
  enable_weather: 'False'
  hide_passcode: 'True'
  panel_title: Brent and Anne's
  shadow_effect: 'True'
  enable_fahrenheit: false
states:
  armed_away:
    immediate:
    - switch.skylight
    - binary_sensor.away_sensor
    - binary_sensor.conservatory_motion_sensor_[Number]
    - binary_sensor.utility_backdoor_[Number]
    - binary_sensor.lounge_lounge_motion_[Number]
    - binary_sensor.office_office_motion_[Number]
    delayed:
    - binary_sensor.away_delayed_sensor
    - binary_sensor.hall_hall_motion_[Number]
    - binary_sensor.hall_front_door_sensor_[Number]
    - binary_sensor.landing_landing_motion_[Number]
    override: []
    pending_time: 2
    warning_time: 2
    trigger_time: 5
  armed_home:
    immediate:
    - binary_sensor.home_sensor
    delayed:
    - binary_sensor.home_delayed_sensor
    override: []
    pending_time: 2
    warning_time: 2
    trigger_time: 5
  armed_perimeter:
    immediate:
    - binary_sensor.perimeter_sensor
    - binary_sensor.hall_front_door_sensor_[Number]
    - binary_sensor.utility_backdoor_[Number]
    delayed:
    - binary_sensor.perimeter_delayed_sensor
    override: []
    pending_time: 0
    warning_time: 2
    trigger_time: 600
users:
- id: 85a1f1f7b2f247dfafe718d0cfe5026d
  name: test
  enabled: false
  code: [CodeString]
  picture: /local/images/ha.png
- id: 36ad4844cafe4f3491e8e4e2ac38e0ff
  name: bart
  enabled: true
  code: '[CodeString]'
  picture: /local/images/hal.png
- id: 2820bcde9f974ef18da3b44b1e494cf3
  name: Legacy API password user
  enabled: false
  code: [CodeString]
  picture: /local/images/ha.png
- id: 9b229b1e281643409c56bcfbb7e0088a
  name: Legacy API password user
  enabled: false
  code: [CodeString]
  picture: /local/images/ha.png
- id: c22b635594b74b56abf2494023c43903
  name: Home Assistant Cloud
  enabled: false
  code: [CodeString]
  picture: /local/images/ha.png
- id: fd199378f989493988de014bdd7e49bb
  name: Hass.io
  enabled: false
  code: [CodeString]
  picture: /local/images/ha.png
- id: 83e1bc958d5b4d5da85a9989f068b857
  name: [My Name]
  enabled: false
  code: [StringCode]
  picture: /local/images/ha.png
- id: 37e7889c63dc41d593507f1d3395e12c
  name: Home Assistant Cast
  enabled: false
  code: [CODESTRING]
  picture: /local/images/ha.png
admin_password: [MyPassword]
code: '[Number]'
enable_perimeter_mode: true
code_to_arm: false
themes:
- name: aaa
  warning_color: '#995BFF'
  pending_color: '#FF2943'
  disarmed_color: '#FF22E6'
  triggered_color: '#FF0000'
  armed_home_color: '#C1B1FF'
  armed_away_color: '#FF8686'
  armed_perimeter_color: '#DAFF9E'
  active: false
  action_button_border_color: '#3ED5FF'
panic_code: '[1234]'
enable_log: true
passcode_attempts: '2'
passcode_attempts_timeout: '10'`

**Comment by akasma74** [comment]
could you edit your post and enclose the content of your yaml file in backquotes to prevent formatting?

**Comment by Buster1959** [comment]
Hi, 
I decided to start from Scratch so removed all of the of the files from the Original Alarm Panel from gazoscalvertos and then all the files I installed from your fork.

Restarted and did a clean install from the Community Integrations.

I have a working solution now so thank you as you pointed me in the right direction.

I have a question:
I only seen Home and Away in the panel even through I have "enable_perimeter_mode: true" and if I go into the Settings Panel and Sensors; anything I set in Perimeter Mode does not take effect.

Keep up the great work: Brent

**Comment by akasma74** [comment]
I'm glag you have managed to get it to work.
Speaking about  "enable_perimeter_mode: true" it's Night mode now, please check the configuration docs.

**Comment by Buster1959** [comment]
Thank you for all of your help.

 

This issue with Night mode was Chrome Caching.  I had enable_night_mode: true but the cache was not letting me see this, Doh!

 

Brent

**Comment by akasma74** [comment]
yeah, I recommend to clear your browser's cache every time you update the integration as it's a (partially) browser-based thing.
