### ISSUE TITLE
Disarm with any password

### ISSUE THREAD

**Issue by thedeejay** [akasma74/Hass-Custom-Alarm#66]
**Your components (from Alarm/Settings/About):**
 - component version 1.11.0

**Platform & Browser:**
 - Platform name & Home assistant version: Ubuntu and 0.91.4
 - Browser name & version: Firefox 68.0.2

**Describe the bug**
I can disarm with any password that is not configured

**Expected behavior**
Only be able to disarm with configured passwords

**Comment by thedeejay** [comment]
Solved it by setting a master password.
It was not enugh with some users defined.

**Comment by akasma74** [comment]
Could you describe your original issue with more details as I don't quite get it?
