### ISSUE TITLE
Issue - home-assistant error on startup

### ISSUE THREAD

**Issue by jkmhb** [akasma74/Hass-Custom-Alarm#7]
receive this error: setup failed for alarm_control_panel: no setup function defined
when I restart home assistant.

I copied all the files as stated in the instructions, and modified the configuration.yaml file. 
I am running Home Assistant in a docker image.

**Comment by akasma74** [comment]
Could you create a proper issue, i.e state versions of the component, alarm panel and HA?
You can find the first two in alarm.yaml and alarm.html accordingly.

**Comment by jkmhb** [comment]
Thank you. I am not near the system right now, so it might take a while. Everything is very current, installed within the past week, though. Thank you for you for you patience, I am new at Github but want to learn. Thanks again,JerryOn May 14, 2019 7:45 AM, akasma74 <notifications@github.com> wrote:Could you create a proper issue, i.e state versions of the component, alarm panel and HA?
You can find the first two in alarm.yaml and alarm.html accordingly.

**Comment by akasma74** [comment]
Do I get it right that it's your initial installation (not an update) and it fails to start the alarm component when you restart HA?

**Comment by jkmhb** [comment]
Yes, this is true. Brand new installation.On May 14, 2019 3:19 PM, akasma74 <notifications@github.com> wrote:Do I get it right that it's your initial installation (not an update) and it fails to start the alarm component when you restart HA?

**Comment by akasma74** [comment]
What's your HA version?

**Comment by jkmhb** [comment]
Your components 
Panel: v1.3.6_ak74
alarm.yaml 1.0.2

Platform & Browser:
Home assistant 0.92.1 running on Ubuntu / Docker

**Comment by jkmhb** [comment]
92.1On May 14, 2019 4:15 PM, akasma74 <notifications@github.com> wrote:What's your HA version?

**Comment by jkmhb** [comment]
Your components
Panel: v1.3.6_ak74
alarm.yaml 1.0.2

Platform & Browser:
Home assistant 0.92.1 running on Ubuntu / Docker

**Comment by akasma74** [comment]
Are you still unable to get it to work?

**Comment by jkmhb** [comment]
I have given up, and am working on manual alarm. This is taking some time.Thanks,JerryOn May 28, 2019 9:59 AM, akasma74 <notifications@github.com> wrote:Are you still unable to get it to work?

**Comment by akasma74** [comment]
Ok, I'm closing the issue.
Feel free to open a new one if you need.
