### ISSUE TITLE
Can disarm with any code

### ISSUE THREAD

**Issue by LEA-Charles** [akasma74/Hass-Custom-Alarm#70]
Your Versions:
This integration: v1.11.2pre1
Home Assistant: v0.103.6
Python: v(3,7,6,final,0)

Action:
Armed into any mode, tested: Night, Home and Away
Entered code 8888 (lots of others tested)  8888 is not a set code

Expected outcome:
Alarm does not disarm

Actual Outcome:
Alarm disarms

**Comment by akasma74** [comment]
I cannot reproduce it.
Could you provide step-by step of _what_ and _how_ exactly it needs to be done.
A lot of people use Lovelace alarm card and they have all sorts of surprises..

You're not the first person who say that. Have a [look](https://github.com/akasma74/Hass-Custom-Alarm/issues/66).

**Comment by LEA-Charles** [comment]
This was resolved with a reboot of HA.  This was the first time that I had setup codes after an install.
