### ISSUE TITLE
Lack a 'resources' directory - installed via HACS

### ISSUE THREAD

**Issue by lancelon** [akasma74/Hass-Custom-Alarm#72]
Installed via HACS and I lack the directory /config/resources/, leading to errors such as

`[log_save] Error occured saving file "/config/resources/bwalarm/bwalarm_log.json": [Errno 2] No such file or directory: '/config/resources/bwalarm/bwalarm_log.json'
`
Not really sure how to correct this. The Hass instance had previously had BWAlarm installed manually as custom component, I then removed the custom component and reinstalled using HACS.

```
Home Assistant: v0.104.1
This Panel: v1.3.6_ak74
Component (Bwalarm): v
Python: v(3,7,6,final,0)
```

**Comment by michaelhdmd** [comment]
Do you have a "resources" folder?  From akasma74's install instructions ... Step 7.

**Comment by akasma74** [comment]
HACS does not create /config/resources/bwalarm/ folder, you need to do it yourself.
Please read installation notes.
