### ISSUE TITLE
MyQ Cover for Garage Door not in sensor list

### ISSUE THREAD

**Issue by Anon0ne** [akasma74/Hass-Custom-Alarm#75]
MyQ Garage Door cover is an attachment for many modern garage door openers. I have one, it's setup in HomeAssistant and it has a state attached to it as well, but I cannot get it into the sensor list for the Alarms. I wanted to include it with my contact sensors.

If more info is required, please let me know.

**Comment by akasma74** [comment]
what is `entity_of` your cover and what states can it be in?

**Comment by Anon0ne** [comment]
cover.garage_door
integration: myq
states:
open
closed

friendly_name: Garage Door
supported_features: 3
device_class: garage

**Comment by akasma74** [comment]
just add it manually to your `bwalarm.yaml,` something like this
```
states:
  armed_away:
    delayed:
    - cover.garage_door
```

**Comment by Anon0ne** [comment]
Thanks, I will try it that way. Just making sure cover would work with it before I put it into config and risk breaking it.

**Comment by akasma74** [comment]
> Just making sure cover would work with it before I put it into config and risk breaking it.

Is will work as soon as it reports different states. And no, you won't break anything by adding a new sensor (provided you do it correctly ;) )

Let me know how it worked out.

**Comment by akasma74** [comment]
I take it works for you.
I'm closing this issue now. Feel free to reopen it or create a new one if you need.

**Comment by Anon0ne** [comment]
If didn't work out but I'll try again. Alarm crashed last time

**Comment by akasma74** [comment]
very interesting. looking forward..
