### ISSUE TITLE
"Overwriting integration alarm" in my log every hassio reboot

### ISSUE THREAD

**Issue by lancelon** [akasma74/Hass-Custom-Alarm#76]
This integration: v1.11.1
Home Assistant: v0.104.3
Python: v(3,7,6,final,0)

Get this in my logs everytime I reboot Hassio.
"Overwriting integration alarm" in my log every hassio reboot
Alarm seems to work ok though.

**Comment by akasma74** [comment]
could you tell me when it started to appear?
also, it would be great to see the actual log content.

**Comment by akasma74** [comment]
I'm closing the issue because of no response.
Feel free to reopen it/create a new one if needed.

**Comment by sparkydave1981** [comment]
This appears to be the same as what I have been seeing recently (currently on HA 0.111.2) with latest version (v1.12.6) of this alarm component installed via HACS.  The alarm component still works fine, just produces the following error on HA startup

> 2020-06-15 11:42:10 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up bwalarm platform for alarm_control_panel
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
>     await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
>   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
>     return fut.result()
>   File "/config/custom_components/bwalarm/alarm_control_panel.py", line 401, in async_setup_platform
>     config={"alarmid": "alarm_control_panel.house"},
>   File "/usr/src/homeassistant/homeassistant/components/panel_custom/__init__.py", line 140, in async_register_panel
>     require_admin=require_admin,
>   File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 190, in async_register_built_in_panel
>     raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
> ValueError: Overwriting panel alarm

**Comment by akasma74** [comment]
@sparkydave1981 nah, please open a new issue providing all details required if you want me to look into it.
It's just because there are many things that can cause issues and without enough information about your configuration I am unable to find the true culprit.
Hope you understand.

**Comment by sparkydave1981** [comment]
no worries, [new issue](https://github.com/akasma74/Hass-Custom-Alarm/issues/105) logged
