### ISSUE TITLE
error alarm_control_panel.bwalarm - Integration '' not found

### ISSUE THREAD

**Issue by mnikser** [akasma74/Hass-Custom-Alarm#77]
- component version [e.g v1.5.0]
Alarm Panel version 1.3.4

**Platform & Browser:**
Hassio 0.104.3
 - Browser name & version
Chrome  79.0.3945.130

**Describe the bug**
2020-01-31 20:25:57 ERROR (MainThread) [homeassistant.components.hassio] Platform error alarm_control_panel.bwalarm - Integration ' ' not found.

This error shows up even if I just do a "check config". I receive configuration not valid with this error. 

**To Reproduce**
For this started after updating HA to 0.104.4 from 0.102.3 and updating the alarm from the master branch. 

**Additional context**
I updated HA to v0.104.3 and the alarm stopped working. I applied the manifest change that is mentioned here, but it didn’t help. The error that I got was that it couldn’t load mqtt. I don’t use mqtt and don’t need it.
Then I decided to completely update my alarm component from the master branch.
![Alarm_error](https://user-images.githubusercontent.com/26015127/73611918-26c40880-45b5-11ea-9ce5-a659d9bbff73.JPG)

**Comment by akasma74** [comment]
> For this started after updating HA to 0.104.4 from 0.102.3 and updating the alarm from the master branch.

if it's from the master branch, its version should be v1.11.2pre1. Could you double check?

**Comment by mnikser** [comment]
I don't know where exactly to look for the version. The panel version is what I picked up from the panel version message. Anyways I think you can actually close this issue. I think the problem was the following line which I think I still had it in my configuration file and not commented out when I was testing:
#panel_custom: !include panel_custom.yaml
Today I did some clean up of my configuration file and I removed these lines completely. Then I noticed the errors message doesn't show anymore, but I got the mqtt error again:
2020-02-02 14:58:32 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of bwalarm. Setup failed for dependencies: mqtt
2020-02-02 14:58:32 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform bwalarm.alarm_control_panel: Could not set up all dependencies.
As I don't use mqtt, I changed the dependency in the manifest to null and then the alarm component started to load again.
![Alarm_info](https://user-images.githubusercontent.com/26015127/73615690-415ba900-45d8-11ea-8290-27fc331879aa.JPG)

The component is working now, but even in the information panel it doesn't show the component version properly.  
Another question, have you disabled Perimeter mode? I can't enable whatever do.

**Comment by akasma74** [comment]
> #panel_custom: !include panel_custom.yaml

oh yeah..

> As I don't use mqtt, I changed the dependency in the manifest to null and then the alarm component started to load again.

the right way is to leave `manifest.json` alone with dependencies as they are and set `enable_mqtt:  false` in your `bwalarm.yaml`



> The component is working now, but even in the information panel it doesn't show the component version properly.

that's because you're not using the latest version. long time ago I changed it to only one version, there is no 'panel`/`component` version anymore.
the version is [here](https://github.com/akasma74/Hass-Custom-Alarm/blob/master/custom_components/bwalarm/resources/panel.html#L8)

> have you disabled Perimeter mode?

I'm starting to think that you're using the original bwalarm..
This component supports Home, Away and Night(ex. perimeter) modes.

**Comment by mnikser** [comment]
Thank you very much for taking care of this component and responding to issues. 

I changed the manifest to its original value and added the directive to disable mqtt in the configuration file. The mqtt error came back:
2020-02-04 19:23:36 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of bwalarm. Setup failed for dependencies: mqtt
2020-02-04 19:23:36 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform bwalarm.alarm_control_panel: Could not set up all dependencies.

Yes, I have this version: 
 const _VERSION = 'v1.11.2pre1';

I am certain that now, I am using your version as I cloned this repository.

**Comment by akasma74** [comment]
> I cloned this repository

when you say cloned, does that mean you use the latest release or you cloned the master branch?
and could you check out [this](https://github.com/akasma74/Hass-Custom-Alarm/issues/63#issuecomment-576031141) just in case?

**Comment by HerkDriver** [comment]
I am also receiving this same error.  I even wiped and did a clean install of HASS then downloaded most current master branch clone.

On reboot, I receive 
--------------
Invalid config
The following integrations and platforms could not be set up:

mqtt
bwalarm.alarm_control_panel
Please check your config.
----------------------------

My bwlarm.yaml only has this for now:
-------------------------
platform: bwalarm
mqtt:
  enable_mqtt: false
-------------------------

Do we need the MQTT addon regardless if we use it in the alarm config?

**Comment by akasma74** [comment]
> I even wiped and did a clean install of HASS then downloaded most current master branch clone.

You mean you made a fress HA install and then manually installed this component from the master branch (not the latest release)?

From the error message I would say you have `dependencies: []` in your `custom_components/bwalarm/manifest.json`.

> Do we need the MQTT addon regardless if we use it in the alarm config?

I don't think we do. Just stopped my add-on and have different errors (cannot connect to MQTT/error talking to MQTT).

By the way, what's your HA version?

**Comment by HerkDriver** [comment]
Home Assistant: v0.104.3

Apologize for the terminology but this is what I did for the component version:
1. Went to https://github.com/akasma74/Hass-Custom-Alarm
2. Clicked green button CLONE or DOWNLOAD and saved to ZIP
3. Installed ZIP contents into HA folders

I was able to launch the alarm panel after installing MQTT addon. Without the addon, the panel will not launch, regardless of the edits to bwlarm.yaml

**Comment by akasma74** [comment]
Thanks for confirming! I never tried it without MQTT broker as my system hugely relies on MQTT so I always have it on.
Will look into it.

**Comment by mnikser** [comment]
Yes, I have used your master branch.

**Comment by akasma74** [comment]
> Yes, I have used your master branch.

If you read our conversation above, the issue might be related to MQTT broker not running.
Could you check that you have a functional one?

**Comment by mnikser** [comment]
I don't use mqtt component neither for alarm nor for anything else. It looks like HA first tries to confirm all components that are listed in the manifest are loaded before loading the alarm component. So if I don't have an mqtt component, even if I have a **enable_mqtt: false** in my configuration, it will fail because the alarm component doesn't get to load to read its configuration.

**Comment by akasma74** [comment]
Well, for various reasons the alarm won't start unless you have a MQTT broker running.
I'm looking into the issue, but at the moment running a MQTT broker is the easiest solution for you.

**Comment by akasma74** [comment]
could you try this [release](https://github.com/akasma74/Hass-Custom-Alarm/releases/tag/v1.12.1) as it contains some MQTT-related fixes?

**Comment by akasma74** [comment]
I'm closing this issue because of no response.
Feel free to open a new one if required.

**Comment by mnikser** [comment]
Sorry, I was away/busy for a while and then totally forgot this as my alarm works when I remove the mqtt from the manifest. I will test and let you know as soon as I can.

**Comment by mnikser** [comment]
Yes, the new release works fine. Thank you again.

**Comment by akasma74** [comment]
cool!
thanks for reporting it
