### ISSUE TITLE
This Component is not working

### ISSUE THREAD

**Issue by jscott304** [akasma74/Hass-Custom-Alarm#78]
When I click on the Alarm button on the side I get a black page saying to look at the logs.
This integration: v1.11.2pre1
Home Assistant: v0.104.3

I've looked through the logs and I'm not seeing anything referencing the platform

Below is the Yaml file:
`platform: bwalarm
name: House Alarm
code: '0001'
code_to_arm: false
passcode_attempts: 3
passcode_attempts_timeout: 10
panic_code: '0002'
enable_night_mode: true
enable_persistence: true

panel:
  hide_sidebar: 'True'
  round_buttons: 'False'
  enable_sensors_panel: enable
  enable_fahrenheit: '0'
  panel_title: Home
  hide_sensors: true
  hide_passcode: 'True'
  enable_clock: 'True'
  cameras: []
  
states:
  armed_away:
    immediate: 
    - binary_sensor.security_front_windows
    - binary_sensor.security_kitchen_windows
    - binary_sensor.security_basement_windows
    delayed: 
    - binary_sensor.security_front_door
    - binary_sensor.security_deck_door
    - binary_sensor.security_basement_door
    override: []
    pending_time: 30
    warning_time: 30
    trigger_time: 600
  armed_home:
    immediate: 
    - binary_sensor.security_front_windows
    - binary_sensor.security_kitchen_windows
    - binary_sensor.security_basement_windows
    - binary_sensor.security_front_door
    - binary_sensor.security_deck_door
    - binary_sensor.security_basement_door
    delayed: []
    override: []
    pending_time: 0
    warning_time: 30
    trigger_time: 600
  armed_night:
    immediate: 
    - binary_sensor.security_front_windows
    - binary_sensor.security_kitchen_windows
    - binary_sensor.security_basement_windows
    - binary_sensor.security_front_door
    - binary_sensor.security_deck_door
    - binary_sensor.security_basement_door
    delayed: []
    override: []
    pending_time: 0
    warning_time: 30
    trigger_time: 600

users:
- id: ####Random####
  name: User 1
  enabled: true
  code: "1234"
- id: ####Random####
  name: User 2
  enabled: true
  code: "5678"`

**Comment by akasma74** [comment]
I need some more information:
- is it a fresh install or update
- was it always like that? if not, when has it changed.
- HA start log would be great, especially with log level of this component set to `debug`

**Comment by mattnic586** [comment]
I have been having the same issue on my install as well. Current I have 1.11.1 installed with 104.3 hass. I have tried 1.11.2pre1 and it has the same issue. This started sometime around Hass 1.03.2 I think. I have set the logger to debug for the component. Where do I find that log?

**Comment by akasma74** [comment]
> Where do I find that log?

<HA config folder>/home-assistant.log

**Comment by mattnic586** [comment]
The component failed to load sometime after the 1.03.2 Hass upgrade. I have the log file, and it's 220MB, should I upload the whole thing or is there a particular part I should post here?

**Comment by akasma74** [comment]
> I have the log file, and it's 220MB

Wow, is it really .log file?
I only need the starting bit up to the point HA stops saying anything about bwalarm.

**Comment by mattnic586** [comment]
Well poop, that's the problem I set MQTT to false and the component loads. Unfortunately for me mqtt is how I active my alarm via node-red. I think I have a work around so I will dig into that.  Thank you for the help.

**Comment by akasma74** [comment]
> I think I have a work around so I will dig into that

Just do [this](https://community.home-assistant.io/t/bwalarm-akasma74-edition/113666/559)

**Comment by mattnic586** [comment]
I added "mqtt" as a dependency in the manifest.json file and set mqtt to true and it is working correctly now! Thank you so much.

**Comment by akasma74** [comment]
I'm glad you're back to bussiness.
Just one thing: in the future please read not only the first post (as the [solution](https://github.com/akasma74/Hass-Custom-Alarm/issues/63#issuecomment-576031141) was at the end of the issue I sent you link to)

**Comment by akasma74** [comment]
I'm closing the issue now as it seems to be resolved (at least for some intrested parties).
Feel free to reopen/create a new one if needed.
