### ISSUE TITLE
MQTT Functionality Broken in 0.105

### ISSUE THREAD

**Issue by e2m32** [akasma74/Hass-Custom-Alarm#80]
**Your components (from Alarm/Settings/About):**
- commit hash: 706885414421450488
- This integration: v1.11.2pre1

**Platform & Browser:**
 - Platform name: 
  hassio v0.105.2
 - Browser name & version: 
  Chrome: Version 79.0.3945.130 (Official Build) (64-bit)

**Describe the bug**
MQTT ARM_HOME, ARM_AWAY, DISARM broken

**To Reproduce**
- Update home assistant to version 0.105.2
- Attempt to arm/disarm from MQTT commands (tested without code required)

**Expected behavior**
Alarm arms/disarms

**Screenshots**

**Additional context**
I tested this with logger prints and the alarm receives the MQTT messages correctly, it looks like `self.async_alarm_arm_home(code)` `self.async_alarm_arm_away(code)` `self.async_alarm_arm_night(code)` `self.async_alarm_disarm(code)` functions are broken or are failing out for some reason. Code now required?

Originally posted here under wrong issue:  https://github.com/akasma74/Hass-Custom-Alarm/issues/63#issuecomment-583553914

**Comment by akasma74** [comment]
I've just updated to 0.105.2 and can reproduce it.
Stay tuned..

**Comment by e2m32** [comment]
You rock! Thanks for the fix 👍Just tested working in 0.105.2 😎

**Comment by akasma74** [comment]
Glad it works for you but it's [not all great](https://community.home-assistant.io/t/bwalarm-akasma74-edition/113666/602) :\

**Comment by e2m32** [comment]
😧Bummer. Yeah, I tried testing the last version on my dev install that doesn't have mqtt setup and it failed. That manifest requires mqtt to be set up... and there is an import of the mqtt component (that used to be under an if statement, but it's commented out). Does there need to be two versions? Or can you get away with some kind of if statement for the manifest 🤔You had to add that to the manifest in the last version for it to work with 0.103.

**Comment by akasma74** [comment]
looking into it, **no** for 2 versions ;)
