### ISSUE TITLE
GUI problem

### ISSUE THREAD

**Issue by glorifiedg** [akasma74/Hass-Custom-Alarm#81]
I've reinstalled bwalarm multiple times and after some time I can't reach the page and see this error in the logs:
`https://XXXXXX.duckdns.org:8123/api/panel_custom/alarm-1.js:647:42 Uncaught TypeError: $(...).width is not a function`

`No matching payload found for entity: Alarme with state topic: home/alarm. Payload: armed_home, with value template None`

`No matching payload found for entity: Alarme with state topic: home/alarm. Payload: triggered, with value template None`

**Comment by akasma74** [comment]
Mate, I can't help you if you ignore the requirements when opening a new issue.
Could you provide all necessary details?

**Comment by glorifiedg** [comment]
Running HA 0.106.5 on ubuntu server 18 on docker. 

Config:
`platform: bwalarm
panel:
  cameras: []
  hide_sensors: false
  round_buttons: true
  hide_passcode: false
enable_night_mode: false
states:
  armed_away:
    immediate: []
    delayed:
    - binary_sensor.porta_da_entrada
    override: []
    pending_time: '30'
    warning_time: '30'
    trigger_time: '300'
  armed_home:
    immediate:
    - binary_sensor.porta_da_entrada
    delayed: []
    override: []
    pending_time: 0
    warning_time: 0
    trigger_time: '300'
  armed_night:
    immediate: []
    delayed: []
    override: []
    pending_time: 0
    warning_time: 0
    trigger_time: 600
users:
XXXXXXXXXXXXXX
admin_password: XXXXX
enable_persistence: true
panic_code: 'XXXX'
code: 'XXXX'
ignore_open_sensors: true
passcode_attempts_timeout: '300'
log_size: '20'
mqtt:
  enable_mqtt: true
  payload_arm_away: arm_away
  command_topic: home/alarm/set
  payload_arm_home: arm_home
  payload_disarm: disarm
  pending_on_warning: false
  payload_arm_night: ARM_NIGHT
  state_topic: home/alarm
  qos: 0
  override_code: false`

It works the first time on a new install of bwalarm but as soon as I setup the config it shows only the title and the botton buttons that do not work, and also no keypad.

**Comment by akasma74** [comment]
Could you edit your post to preserve the config formatting?
Also, does it work locally i.e *without* duckdns?

**Comment by glorifiedg** [comment]
It happens the same on local.

**Comment by akasma74** [comment]
and still, I need to know what version of the alarm and HA you're using - could you post it here?

**Comment by akasma74** [comment]
I'll close this issue now because of no response.
Feel free to open new one or ask on the forum.
