### ISSUE TITLE
Passwords at the attributes tab

### ISSUE THREAD

**Issue by Leon-AroundMedia** [akasma74/Hass-Custom-Alarm#82]
Hello,

If i look at the states page, i can see my passwords for my alarm in the attributes tab. Is there a way to encrypt them or don't show them? It would be very easy to disarm the alarm when you can see the passwords.
Is it possible to show the friendly name of the "changed_by:" attribute?

Regards,
Leon

**Comment by akasma74** [comment]
For the first part of your question - only admins are able to see States. And to access HA you need login/password - is that not enough?

Regarding `changed_by` - could you elaborate your need?

**Comment by Leon-AroundMedia** [comment]
Yess that is enough, I didn't know that only admins can see the states. 

I want to make an automation that send the "friendly name" of the sensor as an notification or TTS message. But i can only get the entity_id of the sensor who triggered the alarm

**Comment by akasma74** [comment]
> Yess that is enough, I didn't know that only admins can see the states.

yes, they changed it recently.
my tablet connects to HA using `user`-type name so no issue here.

> I want to make an automation that send the "friendly name" of the sensor as an notification or TTS message. But i can only get the entity_id of the sensor who triggered the alarm

can you post your automation?

**Comment by akasma74** [comment]
I'll close this issue now because of no response.
Feel free to opena new one or ask on the forum.
