### ISSUE TITLE
Upgrading to version 1.12.2 causes two side menu items for component

### ISSUE THREAD

**Issue by sparkydave1981** [akasma74/Hass-Custom-Alarm#86]
**Your components (from Alarm/Settings/About):**
 - component version 1.12.2

**Platform & Browser:**
 - Platform name: BWAlarm (ak74 edition). Home assistant version 0.106.6
 - Chrome and HA Android app (latest versions, don't have numbers)

**Describe the bug**
Version 1.12.2 of this component changes the side menu address to /custom-alarm.  The old address was /alarm.  Rather than replacing the old side menu item with the new address we now have two side menu items, giving both the old and new addresses, should only have the single side menu item with the new address

**To Reproduce**
1. Go to 'side menu in HA'
2. You will see two 'Alarm' options (should only be one)

**Expected behavior**
Should only be a single 'Alarm' menu item in the HA side menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/7628509/77238377-ec6f0300-6c16-11ea-8a36-b1a1d6fc314d.png)

**Additional context**
Both menu items appear to work, in that they both control the alarm component

**Comment by suds32** [comment]
Same issue here

**Comment by akasma74** [comment]
guys, could you try [this](https://github.com/akasma74/Hass-Custom-Alarm/releases/tag/v1.12.3) release and let me know if it changes anything?

**Comment by suds32** [comment]
No change for me - still has 2 alarm icons

**Comment by sparkydave1981** [comment]
Upgraded to 1.12.3 and restarted HA, cleared cache in Chrome, still seeing two side menu items

**Comment by akasma74** [comment]
ok, cool.
Do you guys happen to have more than one device accessing your HA instance?
Somethig like a tablet/mobile phone. Have you cleared cache/restarted them as well?

**Comment by suds32** [comment]
Tried on pc iPad android phone. Restarted also tested using ha app

**Comment by sparkydave1981** [comment]
I've tried on work PC (multiple Ctrl+F5's) and android app (cleared cache in app settings).

**Comment by akasma74** [comment]
Ok, could you roll it back to v1.12.1 and see if it makes any difference?

**Comment by suds32** [comment]
Rolled back to 1.12.1 all good with just the single alarm icon   -  /alarm
Back to 1.12.3 and 2 icons /alarm and /custom-alarm

**Comment by akasma74** [comment]
Can you guys tell me more about your environment?
HA version, type of installation?

**Comment by suds32** [comment]
Home Assistant 0.107.6
HASSOS 
Supervisor Version 209

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 5.3.0-40-generic
python_version | 3.7.7
timezone | Pacific/Auckland
version | 0.107.6
virtualenv | false

Hope that covers everything

**Comment by sparkydave1981** [comment]
I'm still on HA 0.106.6 (will upgrade next week)

Host System	Ubuntu 18.04.3 LTS
Supervisor v209

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | Australia/Perth
version | 0.106.6
virtualenv | false

**Comment by suds32** [comment]
just wondering if their was a resolution for this

**Comment by akasma74** [comment]
well, it looks like a false alarm so the best course now is to roll back to v1.12.1
I'll clear up the code when I have time

**Comment by akasma74** [comment]
resolved by v1.12.4 release
