### ISSUE TITLE
MQTT Integration Not Working

### ISSUE THREAD

**Issue by jsabia85** [akasma74/Hass-Custom-Alarm#87]
**Your components (from Alarm/Settings/About):**
 - component version: 1.12.4

**Platform & Browser:**
 - Hass.io 108.3
 - Browser name & version: Google Chrome 80

**Describe the bug**
When setting up the MQTT option it looks like it does not work.

I have ring alarm configured with MQTT and it works with the standard alarm control panel but when I put the state and command topic in the MQTT section, arming and disarming does nothing.

**Comment by akasma74** [comment]
Sorry, I do not own Ring alarm and have no idea how it works.
Could you provide me with some info on it.
Also, I need to know what you want to achieve.

**Comment by jsabia85** [comment]
I leverage the ring-mqtt integration to connect to my ring alarm. I have Mosquito MQTT configured for the integration. 

https://github.com/tsightler/ring-mqtt

I am trying to control arm/disarm for the ring alarm via bwalarm, is this possible?

**Comment by akasma74** [comment]
I'm afraid I still need some information to answer your questions.
Could you explain what "standard alarm control panel" did work for you and post appropriate configs? MQTT log when set/disarmed would be very useful, too.

And I need to see your `bwalarm.yaml`.

**Comment by akasma74** [comment]
I'm closing this issue now because of no response.
Feel free to open a new one if you have more information.
