### ISSUE TITLE
GUI display problem

### ISSUE THREAD

**Issue by benmprojects** [akasma74/Hass-Custom-Alarm#88]
**Your components (from Alarm/Settings/About):**
 - component version v1.11.2pre1

**Platform & Browser:**
 - Platform name & Home assistant version - v0.107.7
 - Browser name & version - Chrome Version 80.0.3987.149 (Official Build) (64-bit)

**Describe the bug**
Buttons on screen are very large (see attached screenshot) Looks like a css error

**Expected behavior**
Smaller Icons.

**Screenshots**

![Alarm Buttons](https://user-images.githubusercontent.com/13100801/79285864-22e02b00-7f02-11ea-82d6-d997956bcc99.PNG)

**Additional context**
Also have black text which is difficult to see. (In below screenshot)

![Black text](https://user-images.githubusercontent.com/13100801/79285881-3390a100-7f02-11ea-82c1-193df9fc58a1.PNG)

**Comment by akasma74** [comment]
It's not a CSS error.
It's a new way of displaying key panel as many users complained about small size of digits.
And yes, I know about the black text - it will be changed, just don't know when I'll have time for that.
