### ISSUE TITLE
Since 108.5 stopped working, 

### ISSUE THREAD

**Issue by Klagio** [akasma74/Hass-Custom-Alarm#90]
2020-04-17 09:41:28 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up bwalarm platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 399, in async_setup_platform
    config={"alarmid": "alarm_control_panel.house"},
  File "/usr/src/homeassistant/homeassistant/components/panel_custom/__init__.py", line 140, in async_register_panel
    require_admin=require_admin,
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 190, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel alarm

**Comment by akasma74** [comment]
any chance of being respectful to the maintainer?
if you don not provide the information required when you open an issue, I cannot help.

**Comment by Klagio** [comment]
This component is not working!
Check the Home Assistant log for more details.
Home Assistant: v0.108.5

This Panel: v1.3.6_ak74

**Comment by akasma74** [comment]
Your component is ancient.
Try updating to the latest version according to the instructions.

**Comment by Klagio** [comment]
I am using HACS

BWAlarm (ak74 edition)
It is a fork of "Yet another take on a home assistant custom alarm" that will exist until its author is back to our Earth
Authors:
akasma74
GitHub stars: 48
Last updated: 10 days ago
Installed: v1.12.4
 
Available: (newest: v1.12.4)

**Comment by akasma74** [comment]
Please double check the component's version in Settings -> About.
If it's not  v1.12.4, it looks like issue with HACS.

**Comment by Klagio** [comment]
> Please double check the component's version in Settings -> About.
> If it's not v1.12.4, it looks like an issue with HACS.

where in HASS frontend? When I click settings it does nothing

**Comment by akasma74** [comment]
I don't use HACS but you should see it in your sidebar (Community something?)

**Comment by Klagio** [comment]
anyway I removed everything that was under /custom_components/bwalarm/  and reinstalled using HACS, now restarting

**Comment by Klagio** [comment]
Ok, restarted now seems working, go in settings about

Contribute
Found a bug or got a feature idea? Let's talk about it on Github
Talk to your friends and colleagues about how awesome this alarm and smart panel is
Your Versions:
Home Assistant: v0.108.5

This Panel: v1.3.6_ak74

Component (Bwalarm): v

Python: v(3,7,7,final,0)

**Comment by akasma74** [comment]
bingo. it's not the latest version as HACS reports.
I'd recommend 2 things:
1. Open an issue with HACS
2. Update the component (maybe uninstalling it after backing up your config files and reinstalling via HACS/manually)

**Comment by Klagio** [comment]
> bingo. it's not the latest version as HACS reports.
> I'd recommend 2 things:
> 
> 1. Open an issue with HACS
> 2. Update the component (maybe uninstalling it after backing up your config files and reinstalling via HACS/manually)

but config files is only alarm.yaml, or?

Beside entirely cancel bwalarm directory what I have to do? Where are other files?

**Comment by akasma74** [comment]
yes, alarm.yaml.
btw, did you clear cache?
installation instructions are here on Github.
