### ISSUE TITLE
Alarm fails to load after any update

### ISSUE THREAD

**Issue by suds32** [akasma74/Hass-Custom-Alarm#94]
- Hi since up date to 108 and 109
If I install any update on reboot the alarm has the below error and is not loaded, a second reboot all is good again

Copy to clipboard
Error while setting up bwalarm platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 399, in async_setup_platform
    config={"alarmid": "alarm_control_panel.house"},
  File "/usr/src/homeassistant/homeassistant/components/panel_custom/__init__.py", line 140, in async_register_panel
    require_admin=require_admin,
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 190, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel alarm

**Comment by akasma74** [comment]
When you say "If I install any update", what updates are you talking about?
And does it behave the same way if you just restart HA without installing any updates?

**Comment by suds32** [comment]
Fails after a home assistant update ie going from 0.109.5 to 0.109.6
Just a general restart with no update etc works fine, as does any update within HACS and then restarting

**Comment by akasma74** [comment]
So basically after every HA update you have to restart it one more time to get back to normal, is that correct?
Do you rmember when (roughly) you started experiencing such a behaviour?
Was it HA update or the alarm's update?

**Comment by suds32** [comment]
That is correct, not sure exactly when it started but pretty sure it was fine .108.0

**Comment by suds32** [comment]
Sorry HA update not an alarm update

**Comment by akasma74** [comment]
Is the browser/app you are using to _display_ HA/alarm panel uses admin account or normal user's one?
If the latter, could you try with the admin account?
Also, have you cleared cache of _all_ your browsers/apps accessing HA before reboot?

**Comment by suds32** [comment]
Yes it is an admin account

**Comment by akasma74** [comment]
Ok, thanks.
So after previous HA updates it helped to restart HA twice to get the alarm working.
Is it different with 0.111?

**Comment by fn87** [comment]
My alarm is broken now after 0.111. Restarts does not fix the issue anymore.

**Comment by fn87** [comment]
2020-06-11 11:55:19 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up bwalarm platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/bwalarm/alarm_control_panel.py", line 401, in async_setup_platform
    config={"alarmid": "alarm_control_panel.house"},
  File "/usr/src/homeassistant/homeassistant/components/panel_custom/__init__.py", line 140, in async_register_panel
    require_admin=require_admin,
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 190, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel alarm

This is for an template alarm that are connected to my BWalarm. Could our issues have something to do with the alarm beeing Unknow instead of Unavailable? 
2020-06-11 11:55:42 ERROR (MainThread) [homeassistant.components.template.alarm_control_panel] Received invalid alarm panel state: unknown. Expected: armed_away, armed_home, armed_night, disarmed, pending, triggered, unavailable

**Comment by akasma74** [comment]
> This is for an template alarm that are connected to my BWalarm. Could our issues have something to do with the alarm beeing Unknow instead of Unavailable?

The OP has no such error in his log so I'd say it's a different issue and not the reason why the alarm fails to load. To be honest, those unknown/unavailable states are HA-generated, this component only provides valid [states](https://developers.home-assistant.io/docs/core/entity/alarm-control-panel#states).

**Comment by akasma74** [comment]
@suds32, @fn87 guys, could you overwrite your `custom_components/bwalarm/alarm_control_panel.py` with [this one](https://github.com/akasma74/Hass-Custom-Alarm/blob/only_night_mode_works/custom_components/bwalarm/alarm_control_panel.py), set log level of the alarm to `debug`, clear cache of all your browsers, restart HA and post the relevant log part here?

**Comment by fn87** [comment]
Ok, I did that and strange things are happening. Suddenly my alarm is working as it should again with you new file but BW alarm doesn't load and do not show up in custom components.

I looked at you changed and compered to hat I had and there is nothing in there that would change the actual behavior of the alarm itself. No logs either.

I thing there is something wrong on my end so please disregard my issues for now. Thanks for a quick response and for the file that fixed my alarm...

**Comment by akasma74** [comment]
@suds32 could you tell me why the issue was closed?

**Comment by suds32** [comment]
HI I have removed the Alarm Panel and just gone back to suing the standard Manual Alarm so for me the issue is closed.
Thanks fro your effort in this area

**Comment by akasma74** [comment]
Ok, got it.
That's a shame.

**Comment by akasma74** [comment]
By the way, your issue is identical to [this one](https://github.com/akasma74/Hass-Custom-Alarm/issues/104) and the reason is an old version of the alarm.
