### ISSUE TITLE
Hass-Custom-Alarm needs updated to work with 0.110.0

### ISSUE THREAD

**Issue by awshirley** [akasma74/Hass-Custom-Alarm#97]
**The component:**
This integration: v1.12.4
Home Assistant: v0.11006
Python: v(3,7,7,final,0)

 - Last known working version (if any):
The above components are working until HA is upgraded to 0.110.0

**Your setup:**
 - Home Assistant version: 0.110.0
 - Last known working Home Assistant version (if any): 0.109.6
 - OS: Fedora 32
 - Browser name & version: MS Edge

**Describe the bug**
Get warning message in log, AlarmControlPanel is deprecate, modify BWAlarm to extend AlarmControlPanelEntity
Icons used by BWAlarm fail to load

**To Reproduce**
Upgrade HA from 0.109.6 to 0.110.0

**Expected behavior**
bwalarm to load properly

**Home Assistant log**
2020-05-20 12:29:46 WARNING (MainThread) [homeassistant.components.alarm_control_panel] AlarmControlPanel is deprecated, modify BWAlarm to extend AlarmControlPanelEntity

Screen print showing icons missing:
![image](https://user-images.githubusercontent.com/17732470/82479516-208c6600-9a98-11ea-9665-30b493ef5976.png)

**Comment by akasma74** [comment]
fixed in v1.12.5
